### ISSUE TITLE
Certificate validation behavior of Hono Client when using hono.client.trustStorePath property

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#1002]
Hi Hono Devs,

I've got a question regarding the certificate validation of the hono client.

My setup looks as follows: 
* I'm using the hono client (M8) to connect to an amqp messaging endpoint.
* The amqp endpoint uses tls with an lets encrypt certificate.
* The certificate of the messaging endpoint is expired. 

The client reacts differently depending on the way how I connect. 

* When using the default java trust store (which contains lets encrypt root certificate) the client refuses to connect because of the expired certificate (... ``` Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Jan 17 08:47:54 CET 2019 ```  ...).

* When setting directly the amqp endpoint certificate (the expired one) using the ```--hono.client.trustStorePath=my_cert.pem``` option, the client connects successfully.

Is this the expected behavior of Hono? 

I guess I would have expected the connection to fail as well.

Thanks
Chris

**Comment by sophokles73** [comment]
IMHO this is indeed the expected behavior if the `my_cert.pem` file that you configure as the trust store contains the certificate itself which you want to validate. In that case the certificate itself is the trust anchor and as such is *trusted* unconditionally (as the name implies). In this case there is no *validity period* to verify because the trust anchor only consists of the public key, its algorithm and params. The *validity period* is information that is part of the information that is bound to the public key and which is usually *certified* by the issuer of the certificate. This is also reflected by the fact that the trust anchor for validating a certificate chain can be supplied by means of public keys only.

In your case, or more generally when the peer's certificate has been issued by a public CA, there is no reason to set a specific trust anchor/store on the client.

**Comment by Christian-Schmid** [comment]
Hi,

thanks for the fast clarification!
Makes sense like this too :-)

Thanks
Chris
