### ISSUE TITLE
Protocol adapters do never close "inactive" sender links

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1188]
Hono protocol adapters create AMQP sender links for events and telemetry data for each tenant on the first message for a particular tenant. However, these links get never closed. Would it be an improvement to close these links after some time of inactivity, as links require some memory on both ends? From my point of view this inactivity period might be quite high per default, e.g. one day. 

Background: We execute some system tests periodically with new tenant for each test and delete these tenants afterwards. Over time we get many open sender links in protocol adapters that will never be needed again. These sender links get closed only when the connection gets closed, e.g. when we restart protocol adapter.

WDYT? Is this requirement to specific to our setup or might others also run into this issue?

**Comment by sophokles73** [comment]
Sounds like a reasonable feature to me. I think that we could close links after a much shorter period of inactivity (e.g. 1h) because if the devices of the affected tenant send messages at such a low rate then it probably doesn't hurt much if the downstream link gets established for each individual message.

**Comment by DanielMaier-BSI** [comment]
I am also fine with one hour inactivity period. I had only in mind (I don't know if I remember correctly and if it is still the case) that messages to protocol adapters without pre-established links often fail with no credit issues.

**Comment by sophokles73** [comment]
That is indeed an issue. We might be able to address this with a well-chosen *flow latency* on the protocol adapters. However, if multiple devices of the same tenant start to send a message almost at the same time, then only the first message will be sent over the newly established downstream link whereas messages that have been uploaded afterwards, while the link is not established yet, will get the dreaded 503 ...

**Comment by ctron** [comment]
Maybe that is some configuration value that should be specified on a "per-tenant" basis. As this could be lower for your "test tenants" and higher for normal tenants.

**Comment by sophokles73** [comment]
I do not quite see how it is related to the tenant. The time it takes to receive the first credits depends on the AMQP Messaging Network peer that the adapter is connected to and the network latency between them. But at the time the sender link is established, there is nothing tenant specific happening FMPOV.

**Comment by ctron** [comment]
No, what I meant was the initial time of inactivity before the link gets closed. Instead of using 1 hour or 1 day, this could be configured for the tenant.

As my understanding is, that tenants get created for testing only. And those tenants could actually have a pretty short inactivity timeout (1 minute). While normal tenants could actually have a day (or some other system wide default).

**Comment by sophokles73** [comment]
Fixed via #1416
