### ISSUE TITLE
Delivery outcome is always 'accepted' in northbound side while sending commands

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1289]
A northbound application sends a command to a device. The protocol adapter (tried with _MQTT_ and _AMQP_ adapters) sends back a _rejected_ disposition. This information is not cascaded to the northbound application and thereby the application waits until the time out expires.   

`CommandClient` implementation uses `AbstractRequestResponseClient.sendRequest(Message message, Handler<ProtonDelivery> onUpdated)` to send the AMQP messages. And the delivery state is always received as _accepted_ irrespective of the disposition sent by the protocol adapters.

**Comment by calohmn** [comment]
It looks like the reason is, that the CommandConsumer in the protocol adapter has `ProtonReceiver.isAutoAccept` set in its receiver.
Since the proper delivery update (with `rejected` outcome) by the protocol adapter is done asynchronously and not directly in the message handler of the receiver, the receiver will send an `accepted` disposition frame.
