### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [eclipse/hono#1334]
Hi
The following lines have cryptographic API misuses. <br> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 95: API name => SecretKeySpec:<BR> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 95: API name => SecretKeySpec:<BR> File name => core/src/main/java/org/eclipse/hono/util/MessageDigestPasswordEncoder.java: Line number => 40: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 48: API name => SecretKeySpec:<BR> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 47: API name => SecretKeySpec:<BR>

**Comment by ctron** [comment]
Hello @mhp0rtal,

I am sorry, but I find this report not really helpful. It looks like an output of some tool, without any further explanation. In addition it looks like this tool doesn't work well either.

For example:

> File name => core/src/main/java/org/eclipse/hono/util/MessageDigestPasswordEncoder.java: Line number => 40: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update

https://github.com/eclipse/hono/blob/aa5232e6793d603a24ed3a7b2e8072882c34b316/core/src/main/java/org/eclipse/hono/auth/MessageDigestPasswordEncoder.java#L40

Line 40 in that file is part of comment. Reading further through the code, it also looks to me as if all calls to `update` actually are covered by a final `digest`.

Taking a look at `JWTHelper`:

> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 95: API name => SecretKeySpec:

https://github.com/eclipse/hono/blob/aa5232e6793d603a24ed3a7b2e8072882c34b316/core/src/main/java/org/eclipse/hono/util/JwtHelper.java#L95

> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 48: API name => SecretKeySpec:
> File name => core/src/main/java/org/eclipse/hono/util/JwtHelper.java: Line number => 47: API name => SecretKeySpec:

https://github.com/eclipse/hono/blob/aa5232e6793d603a24ed3a7b2e8072882c34b316/core/src/main/java/org/eclipse/hono/util/JwtHelper.java#L47-L48

This also seems completely unrelated to any security issue.

Maybe you could take the time, and explain what the problem is, so that we can understand and fix the issue.

**Comment by sophokles73** [comment]
@mhp0rtal feel free to reopen if you have more information
