### ISSUE TITLE
Mismatch expectation towards correlation ID

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1339]
Looking at the documentation, it looks like the "correlation id" **optional**:

* https://www.eclipse.org/hono/docs/latest/api/command-and-control-api/#send-a-one-way-command
* https://www.eclipse.org/hono/docs/latest/api/command-and-control-api/#send-a-request-response-command

However, looking at the actual code, this looks different:

https://github.com/eclipse/hono/blob/1574f9b3297d47a94ec465c578d470ffc5d76b97/client/src/test/java/org/eclipse/hono/client/CommandTest.java#L206-L214

https://github.com/eclipse/hono/blob/1574f9b3297d47a94ec465c578d470ffc5d76b97/client/src/main/java/org/eclipse/hono/client/Command.java#L129-L131

**Comment by ctron** [comment]
Ok, this is confusing: The actual thing which should be checked here is "message id". The message id is mandatory.

However, if the message ID is missing, Hono complains about the "correlation ID". This is wrong IMHO.

Also, does it complain about a **missing** ID, in the case the ID is not of type "string". I am not sure why non-strings are rejected, but even in that case it should say "message ID is not of type string".

**Comment by calohmn** [comment]
> https://github.com/eclipse/hono/blob/1574f9b3297d47a94ec465c578d470ffc5d76b97/client/src/main/java/org/eclipse/hono/client/Command.java#L129-L131

The naming of the `correlationId` variable is somewhat misleading here since it contains either the correlation id or the message id.

Regarding a request/response command, it looks to me that we should change the documentation to mark both `messageId` and `correlationId` as non-mandatory in the respective column but write that one of them MUST be set. We have the same kind of pattern already documented for other API requests, e.g. [device registration](https://www.eclipse.org/hono/docs/latest/api/device-registration-api/#assert-device-registration).
For a one-way command, it looks to me that we don't really need the messageId, so we can mark it non-mandatory in the docs.

**Comment by calohmn** [comment]
Regarding the check for type "string": I think we can support the other possible types (UnsignedLong, UUID, Binary) as well, pointing out in the docs that the correlation id of the command response will be the corresponding string value.
