### ISSUE TITLE
Do not use vert.x EventBus in Device Registry anymore

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1346]
As discussed in today's community call, we want to think about dropping the use of the vertx event bus, between the communication endpoints and the service interfaces.

The proposal is to directly wire up the communication endpoint (like the HTTP device management endpoint, or the AMQP registration endpoint) with the service that implements the functionality.

This would reduce the complexity and the code we need to maintain. Also should this improve the performance, as we no longer need to channel everything through the even bus.

**Comment by jbtrystram** [comment]
I can't self-assign this i as I am not (yet?) a commiter, but I am working on this :)

**Comment by sophokles73** [comment]
@dejanb @ctron @calohmn I agree that this would save some code. I wonder, though, if it also removes some of the flexibility we get by decoupling the service implementation from the endpoints via the event bus.
In the current setup we are able to scale up the endpoints independently from the service implementation, i.e. we can have four Verticle instances of the HTTP endpoint while keeping just one instance of the service implementation. In case of the file based registry, this is important because we cannot have multiple instances of it. Otherwise we would need to use the same service implementation instance in all of the HTTP endpoint Verticle instances and start synchronizing method invocations.

I do not really think that the event bus really is a bottleneck (at least for now). Giving up the (deployment) flexibility it provides thus should be considered carefully FMPOV.

I just wanted to bring this up so that we can weigh the pros against the cons and make an informed decision.

**Comment by dejanb** [comment]
@sophokles73 Do you have any particular numbers/experience in scaling file-based registry using event bus? I'm not totally sure it can improve things dramatically in that scenario. Also, how focused should we be on scalability of this use case, on behalf of optimizing the code for production-ready implementations?
IMHO, we should keep the service implementations straight-forward and leave scaling out to deployment (k8s) layer.

**Comment by sophokles73** [comment]
@dejanb I do not think that we have any issue at all with the scalability of the file based example registry, nor does the example registry profit from multiple HTTP endpoint verticle instances.

> IMHO, we should keep the service implementations straight-forward and leave scaling out to deployment (k8s) layer.

Do I understand you correctly in that we should not care about vertical scaling (i.e. using multiple verticle instances) but instead focus on horizontal scaling (using multiple pods) only?

**Comment by dejanb** [comment]
Yeah, that gave us the best results so far in our tests. I don't think event bus adds much benefit in the architecture we are using. But adds some overhead in code and runtime execution path.

**Comment by sophokles73** [comment]
Fair enough

**Comment by jbtrystram** [comment]
I think we can close this 
@dejanb @ctron @sophokles73

**Comment by calohmn** [comment]
@jbtrystram @dejanb I see the EventBus has been removed from the _management_ endpoint classes now. Do you also want to remove it from the other service implementations used for the AMQP endpoints still, or do you want to keep them as is?

**Comment by sophokles73** [comment]
IMHO we should remove the EventBus there as well. Extra care needs to be taken to make sure that we do not run into concurrency issues, though. The service implementation instance would then be accessed from multiple event loop threads ...
