### ISSUE TITLE
Clearly separate HTTP management API from Tenant, Device Registration and Credentials APIs

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1360]
The current implementation of the example device registry uses the same value objects for implementing the management API endpoints as well as the adapter facing APIs.
This seems problematic as it requires these value objects to consider the specifics of all of those APIs' content models instead of focusing on the requirements of the use case that each API has been designed to address. This makes it hard to maintain and evolve the APIs independently from each other and introduces unnecessary dependencies between the clients of the adapter facing APIs and the HTTP based management API implementation.
I therefore propose to create and use a separate set of value objects for the management API that is independent from the existing value objects used by the client(s).

**Comment by sophokles73** [comment]
@dejanb @ctron This is becoming an issue in the context of #1283 where the content model of the responses a protocol adapter expects starts to differ from the content model that is needed for managing tenants.

**Comment by Alfusainey** [comment]
looking around a bit i see the ff. classes:

1. `org.eclipse.hono.service.management.device.Device` for storing device information
2. `org.eclipse.hono.service.management.tenant.Tenant` for storing tenant information (exactly similar to `TenantObject`)
3. `org.eclipse.hono.service.management.credentials.CommonCredential` and its subclasses for storing credentials information

which looks like dedicated value objects for the management API?

**Comment by dejanb** [comment]
Yes, they are dedicated value objects for management API. We left the AMQP value objects in implementation because we wanted to keep the old data format in files and not change AMQP API classes. We should have proper mapping between two. I need to take a look at the exact problem we're having in this case.

**Comment by Alfusainey** [comment]
just to give a small context: 

The `testGetTenantByCa` and `testGetTenantByCaFailsIfNotAuthorized` in the **TenantApiTests**  integration class does:

1.  A tenant add request with a JSON payload containing a single trust anchor and
2. Lookup the tenant using the subject-dn of the trust anchor added in (1)

However, the `TenantObject` class has been modified in #1283 to store a list of trust anchors. When adding the tenant (in step 1),  the `trusted-ca` property of the JSON payload will contain a list as a value (which happens when the TenantObject is serialised to JSON). Thus the add tenant request will fail with a `Bad Request (400)` in the new implementation because the value is not a valid trusted ca specification (see [EventBusTenantManagementAdapter](https://github.com/eclipse/hono/blob/9f64118254bb1f844541dab6ecad026e74f7c3e8/service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java#L309))

Maybe these tests should either use the value objects of the management API or we have two versions of these test cases? should that happen, then I will revert revision 91cf13d since that PR (I assume) should not modify any of the management code base. we created a dedicated [issue](#1359) for such changes

**Comment by ctron** [comment]
But I think we are are changing the data model, then we might need to change the data model of the management API as well. If the tenant supports multiple trust anchors now, then we should change the HTTP API to align with that.

**Comment by sophokles73** [comment]
@ctron that is true. It only seems that the syntax used by the management API and the adapter facing APIs are not (necessarily) the same anymore. In particular, some of the information that is required in the Tenant management API (e.g. the validity period of public key or the *cert* proeprty) will not even be included/supported in the Tenant API anymore. FMPOV it will be easier in the long term to maintain separate value objects than trying to work around the differences within the value object to meet expectations and requirements of both APIs. WDYT?

**Comment by ctron** [comment]
> @ctron that is true. It only seems that the syntax used by the management API and the adapter facing APIs are not (necessarily) the same anymore.

True! And we definitely can split them. And have separate objects. All that I am saying is, that they still should be aligned. If we add a new feature which is relevant to the other API (goes both ways) then we should make changes on both sides.

**Comment by sophokles73** [comment]
@ctron absolutely, I think we're on the same page.

**Comment by Alfusainey** [comment]
@sophokles73 i have seen a few places where the `TenantObject` class is used in tenant api requests and is removing them now.. pls leave this issue open :-)
