### ISSUE TITLE
Device registry doesn't start without a health check port configured

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1369]
The documentation specifies this property as not mandatory. Should we update the doc or is this a bug ?

edit : also , providing a value with an environment variable (i.e. `HONO_HEALTH_CHECK_PORT` do not work anymore)

**Comment by sophokles73** [comment]
Looking at the source code, it seems to me that this property has been required for quite some time. However, we might want to define a (reasonable) default value for it so that we do not need to explicitly set it?

**Comment by jbtrystram** [comment]
I don't see the value of it being a mandatory configuration value. A default value would be enough I think.
I'll have a quick look to add a default value.

**Comment by sophokles73** [comment]
I guess the original idea was to not start the health check server at all, if no port has been configured explicitly. However, I do not see (m)any use cases where you would want to explicitly prevent the health check server from being started. In particular, since we are also using the health check server to expose the scraping endpoint for Prometheus ...
@dejanb @ctron WDYT?

**Comment by jbtrystram** [comment]
Configuring a value as an environment variable doesn't work either for the auth service, so it is not limited to the device registry.

**Comment by sophokles73** [comment]
@jbtrystram please create a new issue for your problems with the environment variables not being picked up. This issue has been created for another reason ...
