### ISSUE TITLE
Telemetry API : useful to have message ID property

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#15]
Inside the payload of an AMQP message for telemetry could be useful to have the "message-id" as property (defined by AMQP spec) but not mandatory (in general the AMQP client library generates a message-id if it's not specified).
It could be useful on the application layer on the service side which gets telemetry messages from Hono.

**Comment by sophokles73** [comment]
I agree that this may be useful to a consumer. In the telemetry API implementation I am currently working on I *forward* the standard AMQP *message-id* property so that a downstream consumer will receive it as part of the message it receives from Hono. However, I think that we should keep it as a message property, i.e. not part of the body which I'd rather have Hono not touch at all.

**Comment by ppatierno** [comment]
@sophokles73 IMHO our APIs have to leverage as much as possible on AMQP features and don't move them inside the body

**Comment by sophokles73** [comment]
That's what I'm saying. The consumer will see all message properties exactly as the sender has provided them. If the sender sets the standard message-id property to a value then the message delivered by Hono to the consumer will also contain this property (**not** as part of the body).

**Comment by hekonsek** [comment]
I assume that we can close this issue then. Client can just optionally include the standard AMQP message ID property. There is no action needed in Hono then.

Feel free to reopen the ticket if I'm missed something :) .
