### ISSUE TITLE
Helm Chart does not install on Kubernetes 1.16

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1534]
This seems to be caused by https://github.com/helm/charts/issues/17511.

If the chart cannot be fixed for the Hono release 1.0.0., this limitation should be added to the deployment guide https://github.com/eclipse/hono/blob/master/site/documentation/content/deployment/helm-based-deployment.md and the minikube setup description in https://github.com/eclipse/hono/blob/master/site/documentation/content/deployment/create-kubernetes-cluster.md (since minikube automatically upgrades Kuberenetes at startup).

**Comment by sophokles73** [comment]
Thanks for reporting, @b-abel :+1: 

The problem seems to be the Prometheus chart which uses the API versions that are no longer supported by Kubernetes 1.16. There already is a [PR](https://github.com/helm/charts/pull/17268) fixing this in the Prometheus chart.
I agree that we should document this limitation in the deployment guide if the PR is not merged until the 1.0.0 release.

**Comment by sophokles73** [comment]
For the time being, we can only document that deployment to Kubernetes 1.16 is quite limited.
Closed via  #1584
