### ISSUE TITLE
Concept documentation "Device Registration" outdated

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1553]
The description in https://www.eclipse.org/hono/docs/dev/concepts/device-identity/#device-registration is outdated. It explains already removed operations in the *Device Registration API* and does not mention the *Device Registry Management API*.

**Comment by sophokles73** [comment]
@b-abel thanks for spotting. Would you like to create a PR fixing this?

**Comment by b-abel** [comment]
Sure.

**Comment by b-abel** [comment]
I'm just struggling a bit with the status of the Device Registry Management API. Is it just a proposal if someone wants to implement a device registry and do not want to invent their own API? Or is there more to it? Making it an "official" Hono device registry?

**Comment by sophokles73** [comment]
Nobody is forced to implement the Management API. However, people are encouraged to implement it so that they can take advantage of (yet to come) tooling for managing the registry content. Also, the example registry and any future (production) registry implementations that come with Hono will implement it.
