### ISSUE TITLE
Support for "secrets" in Docker Swarm and OpenShift for certificates

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#156]
The current "build-docker-image" profiles for the Hono server, router and adapters get the certificates from the "demo-certs" project copying them into the "etc/hono/certs" directory inside the final container.
Docker Swarm and OpenShift provide the "secret" support that should be used instead, even because the OpenShift deployment can't rely on the current demo-certs (I'm using them with the hostname validation disabled).

On the OpenShift side, there is no way (for now) during the build phase to use the fabric8 maven plugin "out-of-box" to read certificate files and create related "secret" YAML file to deploy. So it means that after images creation, it's something that the user needs to do manually with a few OpenShift commands.

What is the way of Docker Swarm you were thinking about ?

**Comment by sophokles73** [comment]
Well, the current docker compose file does not create the secrets within the swarm. Instead, the containers use the default configuration and certs that are part of the built images. In order to use your own configuration and certificates you need to either modify the compose file accordingly (to automatically create the secrets for the stack) or create the secrets manually with separate `docker` commands. I guess this is pretty analogous to what you need to do when deploying to OpenShift.

However, we might be able to create a docker compose file that already contains the secret definition using the Maven Resource plugin.

**Comment by ppatierno** [comment]
But regarding the pom.xml files for Hono server, router and adapters, should we remove the copy of certs in the etc/hono/certs directory inside the built images, in order to use certificates from secrets ?
The way OpenShift works is that, you put certs in a secret than this secret is mounted as a volume allowing the application to read from there. The option could be to leave the certificates into built images (in the etc/hono/certs directory) but then mounting the secret from the volume in a different path (i.e. etc/hono/openshift/certs) and configuring the deployment accordingly (in terms of key store and certs path). Wdyt ?

**Comment by sophokles73** [comment]
That's what I thought as well. Keep the demo certs and config as default but allow for alternative configuration using secrets. This already works with the 0.5-M5 images ...

**Comment by sophokles73** [comment]
@ppatierno is there anything left to be discussed in the context of this issue?
if not, could you please close the issue?
