### ISSUE TITLE
Missing max-ttd attribute in the tenant management API

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1569]
The maximum _time till disconnect_ (`max-ttd`) attribute is missing in the tenant management API. `TenantObject` offers `getTimeUntilDisconnect` to retrieve the `max-ttd` value set at the adapter or tenant level. But currently there is no provision to add this value to the _file based device registry_.

**Comment by sophokles73** [comment]
I do not think that this is entirely true. The Mangement API allows to set *extension* properties on both an `Adapter` configuration instance as well as the `Tenant` object.
The only problem since the migration to the Management API is that the protocol adapters expect to find the property under `adapter[type]/max-ttd` or `tenant/max-ttd` instead of `adapter[type]/ext/max-ttd` or `tenant/ext/max-ttd`. Another question is, whether these are the right places for storing the max-ttd. Since it is not a general resource limitation for the tenant but instead is quite specific to the HTTP adapter, I think that the adapter configuration is still the right place for this property to be set.

**Comment by kaniyan** [comment]
I am aware that we can set any property using `extensions`. I raised this issue as the `TenantObject` expects it under `adapter[type]/max-ttd` or `tenant/max-ttd` and setting this under any other location such as _extensions_ would be still equivalent to not setting this property `max-ttd`.

Also I am not aware of the fact that the _extensions_ section is the intended location to set the `max-ttd`. Hence as part of my PR #1569, I have placed the `max-ttd` property under `adapter[type]/max-ttd` and `tenant/resource-limit/max-ttd` (on par with the property `max-ttl` under _resource limits_).


>
>
>  Since it is not a general resource limitation for the tenant but instead is quite specific to the HTTP adapter

Since it is intended specifically to the _HTTP adapter_, IMHO it would be sufficient to set this property only at the _adapter level_ and doesn't make sense to set it also at the tenant level. WDYT? 

FMPOV for this property the appropriate places would be `adapter[type]/max-ttd` or `adapter[type]/ext/max-ttd`. IMHO setting this property under `adapter[type]/max-ttd` is slightly advantageous as is it is self-explanatory for the users by looking at the schema regarding the data type and and its also straightforward to introduce validations. WDYT?

**Comment by sophokles73** [comment]
> Since it is intended specifically to the HTTP adapter, IMHO it would be sufficient to set this property only at the adapter level and doesn't make sense to set it also at the tenant level. WDYT?

I think so too.

**Comment by sophokles73** [comment]
The original HTTP based API we had for managing the contents of the example registry actually allowed to include *any* additional (custom) properties in both the *Tenant* as well as the adapter configuration. That is because we used the same data model for both, the Tenant API as well as the management API.

With the new Device Registry Management API we introduced the concept of *extensions* to group additional (custom) properties together. The idea behind it is to not clutter the domain objects with custom properties. So, semantically, the two approaches are equivalent, only the location where custom properties are to be defined within the domain object has changed (from `/` to `/ext`).

The Tenant API does not explicitly define the `max-ttd` property, instead, it is defined in the HTTP adapter user guide as a (custom) property that is considered when handling requests from devices.

You are right that this currently doesn't work because we forgot to adapt the corresponding code in `AbstractProtocolAdapterBase` to use the `ext` path for finding the custom property. Thus I proposed to first fix this first, so that the existing functionality works again.

We can then discuss, whether we want to *promote* the *max-ttd* property to no longer be a custom property. However, I do not see why we should because it is still HTTP adapter specific ...

**Comment by kaniyan** [comment]
I will fix this first by changing the `TenantObject` to fetch this property from `adapter[type]/ext/max-ttd`. `AbstractProtocolAdapterBase` fetches the `max-ttd` using the `TenantObject` so its get fixed too.

**Comment by sophokles73** [comment]
@kaniyan can this issue be closed?

**Comment by kaniyan** [comment]
This has been closed via #1572
