### ISSUE TITLE
Helm template file .tar.gz file vs .tgz file. 

### ISSUE THREAD

**Issue by BobOnt** [eclipse/hono#1623]
I am trying to deploy hono using eclipse-hono-1.0.1.tar.gz in the Huawei Cloud. But it requires that the template is provided by .tgz file. The system does not recognize eclipse-hono-1.0.1.tar.gz. how can I convert it to .tgz file?
Thanks

**Comment by sophokles73** [comment]
Have you tried simply renaming it?

**Comment by BobOntario** [comment]
I did . Didn't work.  Apple Mac machine has a facility to convert it. But still not work.  I guess it might be K8S version too low. Any thoughts?

**Comment by sophokles73** [comment]
You will need to provide more detailed information regarding what you are trying to do, which commands you run and what output you get ...

**Comment by BobOntario** [comment]
We tried to use the public cloud and its k8s .  After we created clusters we need, we need create app on cluster. The cloud provides a function to upload app template (e.g. eclipse-hono-1.0.0.tgz). Then the cloud should be able deploy app automatically.  But when I uploaded it, the parsing error. Can't upLoad at all. Not sure what's wrong?

**Comment by sophokles73** [comment]
@BobOntario maybe you can try to put yourself into our shoes and imagine which kind of information one would probably need in order to get an understanding of what you are trying to achieve.

> We tried to use the public cloud and its k8s.

There is no *the public cloud and its k8s*. There are multiple vendors offering different types of services for managed kubernetes. You need to be more specific.

> The cloud provides a function to upload app template

Again, there is no *The cloud* and its hard to see what you mean by *function to upload app template* without being very precise about the cloud provider an the service you are trying to use.

>  But when I uploaded it, the parsing error. Can't upLoad at all.

Sorry to hear that but without detailed logs of which commands you are actually running and what the exact output of those commands is, nobody will be able to help you.

Maybe you also want to take a look at http://www.catb.org/esr/faqs/smart-questions.html which provides useful hints on how to successfully interact with open source communities ...
