### ISSUE TITLE
Question: Customize helm charts for ClusterIP

### ISSUE THREAD

**Issue by selobosi** [eclipse/hono#1636]
We run Hono together with other services behind an [Ambassador](https://www.getambassador.io/) proxy to perform TLS termination. All services should be available via Ambassador only. The Hono Helm charts specify LoadBalancer or NodePort services for adapters etc. We would like to change these to ClusterIP.

What is your preference: Would you like a contribution to your Helm charts to make it possible to change all services to ClusterIP or would you like to avoid such specifics in your Helm charts? Both is fine for us. In the latter case we could use [kustomize](https://kustomize.io/) to change to ClusterIP locally during our installation.

**Comment by sophokles73** [comment]
I am not sure if I fully understand what you are trying to achieve. Do you want to run Hono's protocol adapters *behind* Ambassador? If so, what is the purpose of that? My understanding is that Ambassador (like all service meshes) is mainly useful for HTTP based web services because of its detailed knowledge of how HTTP(S) works. However, since the HTTP adapter is the least useful one in Hono and Ambassador probably won't be very useful with the other adapters, I wonder what you are trying to achieve. Also note that, if Ambassador terminates all TLS connections, then FMPOV you won't be able to authenticate devices by means of client certificates.

**Comment by selobosi** [comment]
Yes, we run all services, including Hono's protocol adapters, *behind* Ambassador to perform TLS termination.

We do that because we run services from multiple sources and each of these sources has its own way of configuring TLS within the services - by using Ambassador to handle TLS, we have a single way of configuring TLS.

Ambassador is able to do [TLS termination for TCP connections](https://www.getambassador.io/reference/tcpmappings) as well.

Client certificates for devices are a point I did not consider yet because we do not use them yet. Thanks for pointing that out! Ambassador can also [authenticate clients that use certificates](https://www.getambassador.io/reference/tls/client-cert-validation), though.

**Comment by sophokles73** [comment]
> Ambassador can also authenticate clients that use certificates, though.

However, it can only do so using a statically configured trust anchor. Another question then is, how the client (device) identity is conveyed to the protocol adapter ...

**Comment by selobosi** [comment]
Yup, that's true, however we're getting away from the original aim of this issue. So it seems like it's ok to not modify the Hono Helm charts right now because more thought would need to be invested into how device authentication would work using client certificates then.

We'll use kustomize to adjust the helm charts locally, for now.

Thanks for investing your time to think through this!
