### ISSUE TITLE
Allow AmqpValue for telemetry data

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#164]
The TelemetryMessageFilter checks the body on type Data. The Qpid JMS uses AmqpValue to encode text messages in AMQP.

**Comment by sophokles73** [comment]
I agree :-) Is there a question behind this statement? You seem to imply that the `TelemetryMessageFilter` should not do this check? The Telemetry API defines it that way,  why can't you simply use a `ByteMessage` in your JMS client ...

**Comment by pellmann** [comment]
In the telemetry API there is the section, which describes different content (content-type) and explicitly says text/plain or application/json - I would not expect, that the data need to be binary encoded in this cases (you maybe need to alter a typical JMS implementation, which just sets a String for JSON object). 
On the other side the spec says later the body must be a AMQP Data section. So the specification together with the implementation is correct. :) 
Is there a reason, why only Data (binary) should be allowed? In my understanding hono does not care about the message, it routes?

**Comment by sophokles73** [comment]
Well, the data is always encoded binary when transferred over the wire. Using the AMQP Data section for conveying opaque data seems natural in order to not require recipients of the message to check for the particular type of body and act accordingly in different ways. The combination of opaque binary data in the body (a byte array in the Data section) and the content type describing how to interpret the payload allows for a canonical process of handling and processing the message FMPOV. 
Using a JMS BytesMessage for conveying a JSON string is BTW very easy, using the `BytesMessage.writeUTF` method ...

**Comment by pellmann** [comment]
I think from the API specification level it is much better to allow just binary data. I only think about the practical use, if someone uses the JMS-AMQP mapping (which might be a typical use case in Java). 
On the code-level it is easy to set binary and not string for JMS. I had situations in mind, where someone just want to change the JMS provider to the qpid-jms to communicate with hono and does not want or could not change the implementation. But this might be a more realistic scenario for the northbound and not the southbound. So I close the ticket for know and we will see if someone comes with this as a real problem in the wild. :)
