### ISSUE TITLE
Hono-Client behind Proxy

### ISSUE THREAD

**Issue by frindt** [eclipse/hono#1652]
I tried to connect to an IoT-Hub using the Hono-Client behind a network proxy via amqp.
The Interface ApplicationClientFactory.create(HonoConnection.class) which returns ApplicationClientFactoryImpl extends AbstractHonoClientFactory. The extended AbstractHonoClientFactory class gives the opportunity using a connect-method from its member instance class HonoConnectionImpl where this class provides a second connect-method with the opportunity passing a ProtonClientOptions-Instance to set Proxy-Configs.

 The problem is, that the AbstractHonoClientFactory only provides the following connect-method without parameters:
` @Override
    public Future<HonoConnection> connect() {
        return connection.connect();
    }` 
Is it possible to add the second parameterized connect-method from HonoConnectionImpl as well?

This would solve using the Client behind a proxy defining the proxy host/port within the ProtonClientOptions as already mentioned.

Thanks in advance!

**Comment by sophokles73** [comment]
I think you should be able to do this already by means of the `HonoConnection.connect(ProtonClientOptions)` method. The method accepts an options object which extends `NetClientOptions` so you can set your proxy objects on it. You code should look something like this:
```
final Vertx vertx = Vertx.vertx();
final ClientConfigProperties props = new ClientConfigProperties();
props.setHost();
...

final ProtonClientOptions protonOptions = new ProtonClientOptions();
protonOptions.setProxyOptions(...);
final HonoConnection con = HonoConnection.newConnection(vertx, props);
con.connect(protonOptions)
.compose(connection -> {
  // successfully connected
  return ApplicationClientFactory.create(connection);
})
.compose(factory -> factory.getOrCreateAsyncCommandClient("my-client"))
})
.compose(client -> client.sendAsyncCommand())
.otherwise(t -> {
  // cannot connect
  // handle exception 
});
```
Make sure to also set the client's AMQP heart beat using the `ProtonClientOptions.setHeartbeat()` method so that the client can detect a stale connection. You may also want to take a look at `org.eclipse.hono.connection.impl.ConnectionFactoryImpl.createClientOptions()` to see which options from `ClientConfigProperties` are copied to the `ProtonClientOptions`.

Let me know if this works for you. Otherwise, IMHO, we should add proxy related proprties to `ClientConfigProperties` in order to provide means to set the proxy at a higher level of abstraction.

**Comment by frindt** [comment]
Thanks for your reply!
This is the point I mentioned. The `HonoConnection.connect(ProtonClientOptions)` offers the possibility using the method with the options or null.
I wrote a Client Class which holds a `ApplicationClientFactory.create(connection);` - Instance. This Instance only offers the option of connect the passed Connection-Instance without setting the possibility setting the options within the `AbstractHonoClientFactory`.
It only offers `@Override public Future<HonoConnection> connect() { return connection.connect(); }`.
What I think is missing in this Class is something a second method like:
`@Override public Future<HonoConnection> connect(ProtonOptions protonOptions) { return connection.connect(protonOptions); }`

**Comment by sophokles73** [comment]
> I wrote a Client Class which holds a ApplicationClientFactory.create(connection); - Instance. 

What is this supposed to mean? Does it hold a reference to an instance of `ApplicationClientFactory`?
Following the instructions I provided before, there is no need to invoke that instance's `connect()` method, because the underlying `HonoConnection` is a*already* connecting, using the `ProtonClientOptions` provided when creating the `HonoConnection` instance ...

**Comment by frindt** [comment]
> Does it hold a reference to an instance of ApplicationClientFactory?

Yes, this "Client-Class" holds a reference to `ApplicationClientFactory`...
with reference to this github repo:
[https://github.com/bosch-io/iot-hub-examples/blob/master/example-consumer/src/main/java/com/bosch/iothub/examples/ExampleConsumer.java](url)
Your example differs to my realization, where mine is pretty close to the given link.

> Following the instructions I provided before, there is no need to invoke that instance's connect() method, because the underlying HonoConnection is aalready connecting, using the ProtonClientOptions provided when creating the HonoConnection instance ...

Absolutly correct - one can connect before passing the instance to the `ApplicationClientFactory` using the `connect(ProtonClientOptions opt)` -method ...
In my case I use the `ApplicationClientFactory` to connect and there is no option to set the ProtonClientOptions afterwards within this Class.
Nevertheless it works fine for me now - still I am just curious why the `ApplicationClientFactory` which uses a `HonoConnection` only provides its simple `connect()` -method and not the `connect(ProtonClientOptions opts)` as well? Is there a specific reason for that?

**Comment by sophokles73** [comment]
That is because the `ApplicationClientFactory` inherits the *connect* method from the (parameterized) `ConnectionLifecycle` interface which per se has no notion of `ProtonClientOptions` ...
