### ISSUE TITLE
Why doesn't AMQP adapter close the connection to the client after it logs "cannot create concurrent command consumer"?

### ISSUE THREAD

**Issue by selobosi** [eclipse/hono#1660]
This is related to  #1509: when a device re-connects to the control/command topic via the AMQP adapter of Hono after it has lost the connection to the internet, it can happen that the AMQP adapter still has an internal command consumer for the old connection and does not create a new command consumer. This can be seen in the logs of Hono's AMQP adapter where "cannot create concurrent command consumer" is printed. The new AMQP connection of the device does however remain, even though it will never receive any commands.

We ran into this issue again because we seem to have room to improve our configuration of idle timeouts in Hono's AMQP adapter and in our devices. We are wondering, however, whether it would be possible for the AMQP adapter to close the (new) connection in such a case. Our device would then attempt to reconnect after a couple of seconds. At least when a number of reconnect attempts have failed, the idle timeout of Hono's AMQP adapter of the old connection would run out and it would drop the command consumer for the old connection so that a subsequent connection attempt would succeed.

Have you previously considered such a mechanism? I had not considered that the AMQP adapter could close the connection so far and thought that it could improve reconnecting because then the AMQP adapter would not fail silently internally but make the failure explicit to the connected device.

**Comment by sophokles73** [comment]
The AMQP connection between a device and the AMQP adapter is not only used for receiving commands but also for publishing telemetry data and events. I therefore do not think that the adapter should close the connection to the device in order to signal that the *old* connection has not timed out yet (from the adapter's point of view).

In fact, the AMQP adapter clearly indicates to the device that the command receiver cannot be opened (yet). Your device can simply react to this outcome by means of re-trying to open the command receiver link. There is no need to close the (new) connection in order to trigger this behavior.
 
We are currently discussing another approach to this problem in #1632

**Comment by selobosi** [comment]
> The AMQP connection between a device and the AMQP adapter is not only used for receiving commands but also for publishing telemetry data and events. I therefore do not think that the adapter should close the connection to the device in order to signal that the _old_ connection has not timed out yet (from the adapter's point of view).

Interesting, thanks for this comment! (We are currently using two `ProtonConnection` instances: one for sending telemetry data and one for receiving commands. On each of the instances we invoke `createReceiver("telemetry")` to receive telemetry data or `createSender(null)` to send commands. So we might consider using one connection for both.)

> In fact, the AMQP adapter clearly indicates to the device that the command receiver cannot be opened (yet). Your device can simply react to this outcome by means of re-trying to open the command receiver link. There is no need to close the (new) connection in order to trigger this behavior.

We were not aware of this mechanism. How does the AMQP adapter indicate to the device that the command receiver cannot be opened (yet)?

CC'ing @YoLieR

**Comment by sophokles73** [comment]
> On each of the instances we invoke createReceiver("telemetry") to receive telemetry data

If your device wants to publish data, it needs to invoke the *createSender()* method with `null` as the target address. The created `ProtonSender` can be used for everything: sending telemetry, events and command responses. You may want to take a look at https://www.eclipse.org/hono/docs/dev/user-guide/amqp-adapter/#link-establishment for details ...

> How does the AMQP adapter indicate to the device that the command receiver cannot be opened (yet)?

Sorry, I was mistaken about the adapter signaling its inability to open the command receiver link. I confused the AMQP adapter with the HTTP adapter. The AMQP adapter will always successfully establish a device's receiver link for consuming commands. Internally, the adapter opens a corresponding receiver link for the device's command address to the AMQP Messaging Network. 
Any commands sent by an application for the device are being routed to *any* adapter instance which has such a receiver link. Thus, as long as any of the AMQP adapter instances has a *stale* connection to the device (from the adapter's point of view), commands might be routed to that *stale* connection's corresponding receiver link instead of the new connection's receiver link and thus not reach the device.

However, as soon as the *stale* connection has been closed by the adapter, new commands should always be routed to the new connection only (because it then is the sole one having a receiver link for the device).

**Comment by selobosi** [comment]
> However, as soon as the stale connection has been closed by the adapter, new commands should always be routed to the new connection only (because it then is the sole one having a receiver link for the device).

That wasn't our impression. But we'll try to reproduce the problem again and report back here.

(Our AMQP adapter is not scaled, i.e. there is only one adapter instance.)

**Comment by sophokles73** [comment]
I you only have one adapter instance and your device opens the new connection and then tries to establish new receiver link for receiving commands, that attempt should fail unless the old stale connection has been closed by the adapter. You device should be notified about this failure by means of the *openHandler* that you register on the `ProtonReceiver` link. You can take a look at [HonoConnectionImpl.createReceiver()](https://github.com/eclipse/hono/blob/e02b3354bbe07ff9f411ac224c3465ddb4ab3b50/client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java#L791) for an example of how to safely determine if the link has been established or not ...

**Comment by selobosi** [comment]
Thank you for sharing the example code, @sophokles73! We were able to add an openHandler to our device's receiver. The device only receives an event when the connection is successfully created but that is sufficient for us to stop reconnecting in this case (and the device now keeps reconnecting every 4 seconds until successful). (Thanks to your hint we are now using a single connection for sending and receiving.)

We are happy that now we have a solution that does not depend on timing even before #1632 is done.

Thank you very much!
