### ISSUE TITLE
Update to Prometheus 2.15.2

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1728]
From version 2.15.0, there are some performance improvements such as 
- Improved PromQL parser performance.
- Reduced memory foot print of loaded Time Series DB blocks.

For more information refer the [release notes](https://github.com/prometheus/prometheus/releases).

**Comment by sophokles73** [comment]
@kaniyan Hono's Helm chart is now maintained in the [Eclipse IoT Packages project](https://eclipse.org/packages/). You should create a PR against their GitHub repo in order to update the Prometheus version.
If we also want to use the updated version on the Hono Sandbox, then you can create a corresponding PR against this (the Hono) repository.

**Comment by kaniyan** [comment]
@sophokles73 :+1: sure

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
@sophokles73 eclipse/packages#34 is not yet merged. After that get merged, I think this issue can be closed.

**Comment by sophokles73** [comment]
This is the Hono GitHub repository. We delliberately chose to move the Helm chart to Eclipse IoT Packages so that it became independent from the Hono code base. I therefore do not think that we should have any issues in the Hono repository dealing with changes that somebody wants to make to the Helm chart in the Eclipse IoT Packages project. WDYT?

**Comment by kaniyan** [comment]
> 
> 
> This is the Hono GitHub repository. We delliberately chose to move the Helm chart to Eclipse IoT Packages so that it became independent from the Hono code base. I therefore do not think that we should have any issues in the Hono repository dealing with changes that somebody wants to make to the Helm chart in the Eclipse IoT Packages project. WDYT?

It makes sense :+1:

**Comment by kaniyan** [comment]
This has been closed via PR #1756.
