### ISSUE TITLE
Determine tenant a device belongs to using device registry

### ISSUE THREAD

**Issue by mhemmeter** [eclipse/hono#1746]
Eclipse Hono is designed for multi-tenancy. All functionality of Hono is provided in the context of a previously created tenant. This only excludes the creation of a tenant.

If registered devices connect to Hono the Protocol Adapters determine the tenant a device belongs to. This is done as part of establishing a connection and the concrete mechanism depends on the authentication scheme that is supported by an adapter (username/password, client certificate, ...). However the tenant relation is as of today always static. It is part of the username (that is  _auth-id@tenant_) or is determined implicitly as part of validating a client certificate using a registered trust anchor.

This is fine, however I see the following use case where we need a more dynamic approach:
- An end-to-end solution provider offers its solution to different customers and makes use of the multi tenancy concept of Hono (one customer of the solution provider equals to one tenant)
- During the production process it is not known to which customer of the solution provider a device will be assigned later on, so its not clear to which Hono tenant a device belongs
- Nevertheless devices are supposed to connect in a secure manner. This means:
-- For username/password based authentication tenant cannot be part of username 
-- For client certificate based authentication there is a single trust anchor of the solution provider instead of a tenant specific one for each customer of the solution provider

That problem can be addressed by updating the credentials via a firmware update of the devices after they have been assigned to a customer. I'm envisioning however a _lightweight_ approach using the device registry. If an implementation of a device registry ensures uniqueness of device identifiers across tenants, the Protocol Adapter could query as part of the authentication process the tenant a device belongs to and could use that information to establish the tenant scope.

What do you think? Does that make sense and/or does such an approach break the multi-tenancy concepts of Hono? Any other ideas to address the use case?

**Comment by sophokles73** [comment]
I see the problem at hand and also recognize it as a valid use case. The approach you are presenting to address the issue, however, has some problems FMPOV.

> If an implementation of a device registry ensures uniqueness of device identifiers across tenants, the Protocol Adapter could query as part of the authentication process the tenant a device belongs to and could use that information to establish the tenant scope.

The device's identity and the tenant that the device belongs to is determined as part of the authentication process as you correctly point out. Thus, it is the *authentication identifier* that would need to be unique among all tenants, not the *device identifier*, which is resolved as the result of successful authentication.

For a green field solution this might be possible by using e.g. UUIDs as authentication identifiers during the production process. However, using this approach would require *all* devices hosted on the Hono instance to have unique auth-IDs so that the device registry implementation could always use the same strategy of looking up credentials across all tenants instead of within a single tenant only. For username/password based authentication this might do the trick already.

For client certificate based authentication things are a little different because it is unclear which properties of the client certificate should/could be used for determining the tenant. Thus, it would seem feasible to pass the whole client certificate into the *get Credentials* call and let the Device Registry figure out how to determine the device (and tenant).

All of this seems possible but would require changes to the Credentials API that allows a client (an adapter) to query data for *all* tenants instead of just the tenant that its sender link is scoped to. The links are scoped to individual tenants in order to more easily enforce access policies. However, since we now discourage people to create custom protocol adapters in favor of protocol gateways, this becomes less of a problem.
The protocol adapters would need to be adapted to not try to determine the device's tenant themselves but to always delegate this task to the Credentials API by including the device's credentials *in toto* instead of extracting the auth ID from a username or using the issuer DN of a client cert to look up the tenant.

Nevertheless, I also see a more generic and more versatile approach to the given problem. Hono could provide a new *bootstrapping* endpoint to devices which they can use to initially connect to and retrieve tenant scoped credentials. This bootstrapping endpoint could use arbitrary properties of the client to identify the device and determine its tenant. It could then hand out fresh credentials to the device along with the protocol adapter's endpoint URL that they should connect to for publishing data. The bootstrapping endpoint could also be used to perform key rotation, i.e. to provide devices with new credentials periodically. A task that is completely left to the device manufacturer today.

The bootstrapping endpoint could be part of the protocol adapters themselves (in order to provide the endpoint using the device's transport protocol) or could be provided separately using a single transport protocol, e.g. HTTP. The former seems to be more desirable for device firmware developers since it doesn't require implementation of multiple protocol stacks.

**Comment by mhemmeter** [comment]
Thanks for the feedback and sorry for the late response. I think we should continue the discussion as follows:
1. For the original discussion of determining the tenant a device belongs to using device registry we can continue to use this issue.
2. For the bootstrapping mechanism I see a lot of demand from different stakeholders and I think such a feature is very valuable. I will create a new issue to discuss this further.

**Comment by mhemmeter** [comment]
After having re-discussed this topic with the main stakeholder we can close the issue for now. The more generic approach of providing a bootstrapping endpoint seems to be more promising due to its flexibility.
