### ISSUE TITLE
Hono JARs contain open tracing API classes

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1775]
Currently the `hono-core` jar file contains classes from opentracing (`io.opentracing`).

This can be problematic when you want to override the dependency, as the currently build process always includes those.

My proposal would be to either remove them, or add a maven profile, which embeds those, only when explicitly requested.

**Comment by sophokles73** [comment]
We included the classes because the Opentracing jars are not proper OSGi bundles, so in order to use the core module in an OSGi environment, we included the classes here.
The people already using the core module as a bundle in an OSGi framework are currently relying on this fact. So, in order to make transition easier for them, I suggest that we instead move the bundle creation to a maven profile which is active by default but which can be deactivated by setting a property. Would that work for you @ctron?

**Comment by ctron** [comment]
That would create another problem, as we would have different artifacts then for upstream (EnMasse) and downstream (AMQ Online). In upstream we would like to non-rebuild Hono, but use the already released Hono artifacts. However they would the still contain OpenTracing. Downstream would miss those classes, as we would re-build with this new profile.

Wouldn't it be possible to create two JARs? One containing the embedded JAR, for using with OSGi, and one without them. We could use a classifier in order to distinguish them. It would also be fine if the "vanilla" JAR has the additional classifier, as we still should be able to pull the same dependency upstream and downstream in that case.

**Comment by sophokles73** [comment]
@ctron is this still an issue? Didn't you already remove the OpenTracing classes from the JARs?
