### ISSUE TITLE
Prometheus resource limit check ignoring minimal message size

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#1823]
At the moment minimal message size is considering only when we query Prometheus but also this should be taken in account when we cheeking if the message exceeded allowedMaxBytes. 
Like reference in the code  please see [PrometheusBasedResourceLimitChecks.java#L457](https://github.com/eclipse/hono/blob/master/service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java#L457)

**Comment by kaniyan** [comment]
Currently the payload size of the incoming messages are calculated and stored in the Prometheus server based on the configured minimum message size for each tenant. When a message is received from a device, the protocol adapter currently uses the payload size of that incoming message plus the data volume already used up by that tenant(from Prometheus server) to validate the message limit. Instead of using the actual payload size of the incoming message, a payload size should be derived based on the configured minimum message size and be used for the message limit validation. I will fix this.

**Comment by kaniyan** [comment]
> 
> 
> Currently the payload size of the incoming messages are calculated and stored in the Prometheus server based on the configured minimum message size for each tenant. When a message is received from a device, the protocol adapter currently uses the payload size of that incoming message plus the data volume already used up by that tenant(from Prometheus server) to validate the message limit. Instead of using the actual payload size of the incoming message, a payload size should be derived based on the configured minimum message size and be used for the message limit validation. I will fix this.

Currently message size is being calculated based on the configured minimum message size and stored in the Prometheus server as expected. When a new message arrives, the payload size of this message should also be derived from the minimum message size configuration for the limit checks and it will be fixed.

**Comment by sophokles73** [comment]
Fixed via #1825
