### ISSUE TITLE
Update data volume resource limits cache with each message 

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#1824]
Current data volume (in bytes) sent by a tenant is queried from Prometheus and stored locally till cache time out expiration. But, why we are not updating this locally with each  incoming message(i mean payload size calculated based on _minimum message size_ ) after when the cache will be expired this value will be overridden with data from Prometheus. 
In case when this data will be dynamically updated the tolerance rate of messages that exceeded data limits will be very low.

**Comment by sophokles73** [comment]
@fkaltner does this sound like something you might be interested to work on?

**Comment by sophokles73** [comment]
@fkaltner then please leave a comment so that I can assign the issue to you ...

**Comment by fkaltner** [comment]
The intricacies of GitHub, next time I'll leave a written "thumbs up"... 😄

**Comment by sophokles73** [comment]
Based on the discussion in https://github.com/eclipse/hono/pull/2078#issuecomment-660978460 and the fact that we have updated the cache to retrieve the used-up data volume in the background (#2652), I wonder if we still want to follow through with this issue.

FMPOV we can close it as *won't fix* and also close the corresponding PR (#2078).
WDYT @kaniyan @fkaltner @calohmn ?

**Comment by fkaltner** [comment]
In my opinion (see https://github.com/eclipse/hono/pull/2078#issuecomment-660990005) the accuracy of the current implementation is sufficient. Hence I also think this issue can be closed.

I think that https://github.com/eclipse/hono/pull/2652 does not address this issue as far as I understood it by reading the description. In order to do so, the cached values (in the Caffeine cache) needed to be updated when a new message is processed in between the asynchronous loading from Prometheus. Still, I do not think it would be worth the added complexity.
