### ISSUE TITLE
Secure Mongo DB based registry's Management API with HTTP Basic Authentication

### ISSUE THREAD

**Issue by mhemmeter** [eclipse/hono#1864]
The current implementation of the Device Registry doesn't provide any security, meaning the API can be accessed without authentication. Therefore it cannot be used in production. Originally it was planned to address this topic in #1679, but to reduce the scope of the issue I created this follow-up. 

For securing the API I would propose to start with a mechanism following the Basic Authentication Scheme as it is straightforward and simple. We can later on extend and support additional authentication schemes, e.g. Bearer Tokens.

**Comment by ctron** [comment]
I think @dejanb already started to port the changes we have made in EnMasse, adding Bearer token authentication via Kubernetes, to Hono. So that should a) introduce all the security checks, and b) allow for adding basic authentication as well.

**Comment by mhemmeter** [comment]
Sounds good. Is there already an issue or initial pull request for this in the Hono project (I did not find one but maybe I have overseen it)? We could also us this issue to move forward.

**Comment by dejanb** [comment]
@mhemmeter the support for plugging authentication handler is there since #1453. We're using it in enmasse, but hasn't been used in Hono so far. I agree that we can start with using basic auth for starters. We should be able to use Vert.x provided one, so it shouldn't be too much work to do that.

And I can adapt k8s token based implementation from enmasse to more general purpose one in Hono in the future.

**Comment by mhemmeter** [comment]
Perfect, I only looked at the open issues and PRs :-). So let's take it forward from that point then.

**Comment by dejanb** [comment]
@mhemmeter opened #1867 to track k8s auth integration

**Comment by sophokles73** [comment]
closed via #1918
