### ISSUE TITLE
Security vulnerability in Hono 1.2.1

### ISSUE THREAD

**Issue by gongzhao1** [eclipse/hono#1895]
Hi All,
We used Sonatype CLM to scan the jar package in Hono ’s docker image and found some of the security vulnerabilities and open source license issues。
**Security Issues:**
| Problem Code | Component |
| ---- | ---- |
| CVE-2019-16942 | com.fasterxml.jackson.core : jackson-databind : 2.9.10 |
| CVE-2019-16943 | com.fasterxml.jackson.core : jackson-databind : 2.9.10 |
| CVE-2019-17531 | com.fasterxml.jackson.core : jackson-databind : 2.9.10 |
| CVE-2017-18640 | org.yaml : snakeyaml : 1.25 |

**License Analysis**
| License Threat | Component |
| ---- | ---- |
| EPL-2.0, Not Provided | corg.eclipse.hono : hono-demo-certs : 1.2.1 |
| EPL-2.0, Not Provided | org.eclipse.hono : hono-legal : 1.2.1 |

Are there any plans in place to fix these issues by upgrading or something?

**Comment by sophokles73** [comment]
Hi,

thanks for sharing your concerns. As far as I can see, Hono is not affected by any of the potential vulnerabilities around jackson-databind because Hono doesn't fulfill their requirements. 
Hono uses snakeyaml only during startup for reading configuration variables from a file provided by the system administrator. So I guess unless the admin is the attacker, there shouldn't be an issue.
Nevertheless, we will upgrade the corresponding components in the upcoming 1.2.2 service release.

In the future, please use the [dedicated channel provided by the Eclipse Foundation for reporting (suspected) security issues](https://eclipse.org/security/) in order to provide us with some time to create a fix before making the vulnerability public.

**Comment by gongzhao1** [comment]
Hi sophokles73,

Actually, we also did a small-scale penetration test ourselves and also found a medium-level vulnerability of MQTT adapter, which I will report in accordance with the reporting process.

**Comment by sophokles73** [comment]
Thanks a lot :+1:
