### ISSUE TITLE
coap-adapter, 4.01 - DTLS session does not contain authenticated Device

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1914]
In some rare cases I get responses with

4.01 - DTLS session does not contain authenticated Device

FMPOV, that is caused by a timeout in the second request of the `DefaultDeviceResolver`. If the first would fail, then the handshake would not succeed and therefore no response would be received.

Is it possible to enable the "amqp client caching" used there with a short cache timeout (e.g. 30s) in order to prevent the coap-adapter from failing with that 4.01 ?

**Comment by sophokles73** [comment]
Can you please describe what you are observing and why you believe that it is a problematic/erroneous behavior?

**Comment by boaks** [comment]
> coap-adapter

> I get responses

> 4.01 - DTLS session does not contain authenticated Device

I'm not sure, what should be missing here? 

> FMPOV, that is caused by a timeout in the second request of the DefaultDeviceResolver. If the first would fail, then the handshake would not succeed and therefore no response would be received.

That's my analysis. Let me try to fillin some more words. The `DefaultDeviceResolver` sends two requests for the same authid/tenant (agreed?).
I consider the first  to be in time, therefore the handshake finished successfully and the request and response could be exchanged (agreed?). 
If the first would have failed, that exchange would fail, and no response would have been received  (agreed?).
The error response then points to the second request of the `DefaultDeviceResolver`, which, according the comment there

```
// client will only wait a limited period of time,
// so no need to use get(Long, TimeUnit) here
```

may timeout. So my assumption is, the authid/tenant works (therefore the response), the second request times out, therefore the 4.01, and enable a caching with a short cache-timeout may help, if the analyis is right.

**Comment by boaks** [comment]
> believe that it is a problematic/erroneous behavior?

Why should someone be irritated by a 4.01 (pointing to an authentication issue), if this is the result of timeout?

**Comment by boaks** [comment]
> rare

I have seen this twice in a couple of weeks. Therefore detailed logs are not available.
It seems for me to be much easier, to try to configure the cache, and see if the problem still exists, than to explicitly try to reproduce it.

**Comment by sophokles73** [comment]
I am sorry, but I still don't understand what you are talking about. Is this about a single request from a device and the DTLS handshake that is involved? Or are we talking about multiple requests (and handshakes) from the same device?

**Comment by boaks** [comment]
The last occurrence yesterday was with multiple clients (about 1000), each sending multiple request (in seconds). Generally the clients will start a handshake again, if the coap-request times out. I don't know, if that was the case. The topic of my tests wasn't to reproduce the rare behavior, therefore the exactness of that information may be doubted.
If you have an other theory, what causes a 4.01, maybe you explain it?

**Comment by sophokles73** [comment]
Well, before coming up with any theories, I first need to understand what you are doing and what the observed behavior is, right? Then we can discuss if this behavior differs from the expected behavior and then we can start to discuss whether that is indeed unexpected and, if so, what the reason for it might be and what potential fixes might be. My understanding of your initial post was being offered a fix for a problem, that I didn't know anything about.

That said, my understanding now is:
1. A client tries to upload messages at a rate > 1 msg/s
1. In almost all cases, the upload succeeds.
2. Very rarely, the upload fails due to a failed DTLS handshake.
3. You suspect, that when the handshake fails, it is because the *DefaultDeviceResolver.getInfo* method returns an empty map.

Is that correct?

**Comment by boaks** [comment]
> Very rarely, the upload fails due to a failed DTLS handshake.

That's not the case! The handshake doesn't fail, it succeeds.

> The DefaultDeviceResolver sends two requests for the same authid/tenant (agreed?).

I guess, the misunderstanding is here:
These two requests are used by **ONE** handshake! the first looks up the secret, the second the "additional info". you may see that in jaeger.

**Comment by boaks** [comment]
> Is that correct?

No.

**Comment by sophokles73** [comment]
You see how important it is to first talk about the context? ;-)

Ok, so the invocation of the *DefaultDeviceResolver.getKey* method succeeds and then, at the end of the handshake when the session is established, you suspect the *DefaultDeviceResolver.getInfo* method to return an *empty* AdditionalInfo object, right?

**Comment by boaks** [comment]
> Ok, so the invocation of the DefaultDeviceResolver.getKey method succeeds and then, at the end of the handshake when the session is established, you suspect the DefaultDeviceResolver.getInfo method to return an empty AdditionalInfo object, right?

Yes, that's how I interpret it.

**Comment by sophokles73** [comment]
Do you have a log or Jaeger trace for when that's happening?

**Comment by boaks** [comment]
> You see how important it is to first talk about the context? ;-)

The context is simple, maybe the special behavior of the `DefaultDeviceResolver` inhibits to understand, that the context is simple.

**Comment by boaks** [comment]
> Do you have a log or Jaeger trace for when that's happening?

The two request?

Or the 4.01?

> I have seen this twice in a couple of weeks. Therefore detailed logs are not available.

**Comment by sophokles73** [comment]
You mentioned that you can see it in Jaeger, so, a Jaeger trace for when this actually happened would be great.
The Credentials client already puts all responses from the Credentials service into a local cache at the adapter side. The default max size is 1000, i.e. if you use more than 1000 distinct devices in your test scenario, then you might run into a situation where the credentials info gets evicted from the cache right between the invocations of *getKey* and *getInfo*. This seems highly unlikely, though. Even if this is the case, then I do not see why retrieving the credentials from the Credentials service again should fail or time out. Without a trace or log it is hard to say what has actually happened. The only thing you could potentially do is either increasing the max cache size to a value greater than the number of distinct devices you use or reduce the number of distinct devices to under 1000.
In general, it should not be a big problem if this happens very sporadically. However, we might want to change the behavior of the CoAP adapter in this case so that it doesn't look to the client as if authentication failed but instead maybe return a 5.03 or 5.00. WDYT?

**Comment by boaks** [comment]
> These two requests are used by ONE handshake! the first looks up the secret, the second the "additional info". you may see that in jaeger.

It's easy to see in jaeger, that two requests are used by the `DefaultDeviceResolver`

**Comment by boaks** [comment]
> reduce the number of distinct devices to under 1000.

OK, I will do that in future tests.

You're sure, that the cache is enabled?
Just to mention, if you enable jaeger you see the two DefaultDeviceResolver requests in all handshakes. I'm not sure, if that also shows, if the response is cached or not.

**Comment by sophokles73** [comment]
According to https://www.eclipse.org/hono/docs/dev/admin-guide/common-config/#credentials-service-connection-configuration this should be the case if the registry implementation includes a permissive cache directive, i.e. something other than `no-cache` ...

**Comment by boaks** [comment]
I captured some jaeger traces.

[getCredentials.zip](https://github.com/eclipse/hono/files/4517119/getCredentials.zip)

The traces of both requests shows "cache_hit false".
Both calls use are using the same tenant-id (DEFAULT_TENANT), the same type "psk", the same auth-id (sensor1), I also adapted the code to use the identical (same this) JsonObject for the clientContext.

From your link:

> The adapter caches the responses from the service according to the cache directive included in the response. If the response doesn’t contain a cache directive no data will be cached.

Let me guess, for PSK the response doesn't included that directive?

**Comment by sophokles73** [comment]
If you are using Hono's example registry, then it should include a permissive cache directive. For other registry implementations I can't tell ...

**Comment by boaks** [comment]
Did you try it on your own? Installing the helm chart of hono packages, send a dtls request and check the jaeger traces?
I
'm not aware, that I changed something from that setup.

Since the start of this issue, I claim, that these requests seems for me to be not cached.
You insist, that I should give you more information, insights and traces. 
But, did you simply check, if your assumption, that the caching is enabled, is right?

**Comment by sophokles73** [comment]
The cache is definitely enabled. However, I have taken another look at the example registry and it indeed uses `no-cache` for PSK credentials because they are clear text and we thus originally deemed it to not be a good idea to cache them. Note, that this is only true for the example registry, i.e. other registry implementations may or may not use `no-cache` for PSK credentials ...

**Comment by boaks** [comment]
> Is it possible to enable the "amqp client caching" used there with a short cache timeout (e.g. 30s) in order to prevent the coap-adapter from failing with that 4.01 ?

Therefore I proposed a short cache timeout. In my opinion, that will reduce the risks here. Or is the cache not cleaned up on timeout?

**Comment by sophokles73** [comment]
I agree that this would reduce the risk, but
1. the protocol adapter has no control over the cache directive being used, this is the responsibility of the Credentials service implementation and
1. the local cache implementation only evicts entries on access, i.e. when reading an entry the expiration time is checked and the entry is removed, if the entry has expired. So, in theory, an entry could live forever in the cache, if it never gets accessed again.

**Comment by boaks** [comment]
OK, then I think, add a "size limited Map" of 
(auth-id@tenant-id => device-id, without secret) in the future will be the best solution.
