### ISSUE TITLE
Define a set of authorised characters for device Id, auth-id and tenant id

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1956]
Right now there is now defined set of authorised characters for those identifiers in the documentation, except that semicolon is forbidden for auth-id and a note that advise to use `[a-zA-Z0-9_-]`. 

To create a UI it would be good to have a defined regexp so the input can be validated when creating a new device for example. 

I propose to set `[a-zA-Z0-9_-]` (maybe with a dot `.` in addition) as the accepted characters in the documentation for device ID, auth-id and tenant ID.

**Comment by calohmn** [comment]
@jbtrystram @dejanb @sophokles73 
As brought up in the Hono gitter channel, I think a release notes entry is missing here about a Device Registry API change, also informing how to configure the tenant/device pattern, so that e.g. systems using Ditto can still create devices (with a colon in the id).

Regarding the changes in the `device-registry-v1.yaml`, defining the schema pattern for the device and tenant identifier:
Isn't this an inconsistency that the patterns are explicitly defined in the API, while they can still be adapted using the configuration properties? I mean, a device registry that has overridden the patterns using the properties doesn't conform to the API anymore, does is?
Maybe we should therefore remove the device/tenant patterns from the API spec?
I think it would at least be good to allow the colon in the device id, to conform with Eclipse Ditto.
WDYT?

**Comment by sophokles73** [comment]
> Regarding the changes in the device-registry-v1.yaml, defining the schema pattern for the device and tenant identifier:
Isn't this an inconsistency that the patterns are explicitly defined in the API, while they can still be adapted using the configuration properties? I mean, a device registry that has overridden the patterns using the properties doesn't conform to the API anymore, does is?

I agree. This seems rather inappropriate.

> Maybe we should therefore remove the device/tenant patterns from the API spec?

Yes, I agree.

> I think it would at least be good to allow the colon in the device id, to conform with Eclipse Ditto.
WDYT?

The default pattern used in the registry should do so, yes.
