### ISSUE TITLE
AMQP APIs : messages body

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#20]
As you know the body of an AMQP message can be Data (raw binary), AMQP Value and AMQP Sequence (a sequence of AMQP Value).
If our APIs should be strictly AMQP based it means (to me) that other than protocol features in terms of communication we have to use the builtin type system it provides.

It's true that a lot of users prefer to have body formatted in a well known way using for example JSON or XML; it means that this data can be transferred as raw binary AMQP Data but of course as String type AMQP Value as well (my opinion ? I don't like last solution :-))

I'm for using the AMQP type system and AMQP Value for structured types that users want to send/receive to/from Hono. It means mapping their data to Map, List and so on (in AMQP). Every JSON and/or XML representation can be mapped in this way.

Of course, what does it mean ? 

If users prefer to use AMQP direct connection then they have to use AMQP Value as body message (mapping their data on Map, List and so on).
If they prefer to use adapters (HTTP; LWM2M and so on), they can use JSON or XML (or other) and Hono has to map to native AMQP Value.

The other solution (as describe in the current APIs) is to use content-type and then AMQP Data.

Currently my opinion is to have internal Hono system leverages as much as possible on AMQP and on its type system too.
Btw ... I'm thinking about that ... just writing to have your opinions here :-)

**Comment by sophokles73** [comment]
I don't think that we should make any difference between devices connecting to Hono directly and devices connecting via Protocol Adapters. Having said that I also do not want to Hono to have to actively do anything with the message payload at all. Instead, I would rather have Hono being able to consider the payload an opaque byte array that can be forwarded to consumers *as is*. We certainly do not want to start mapping hence and forth any potentially structured data contained in the payload. If a client wants to use such structured data, e.g. JSON or XML it is free to do so and provide the payload as a Data section containing the *byte array* representation of the JSON/XML.

As Gordon pointed out in one of the questions he raised on the mailing list, we should use the *content-type* property to describe the payload type and encording so that a consumer will be able to interpret the payload data correctly.

I do not see how the AMQP defined type system of Map, List etc. could be useful in this context. But maybe my understanding of this is simply too limited (yet) ...

**Comment by ppatierno** [comment]
You are absolutely right ... my opinion was only related to leverage on AMQP features as whole if it's our "internal" Hono protocol. I mean ... JSON and XML aren't part of AMQP specification ... Map and List are part of AMQP type system.

As I said I was just thinking and sharing my thoughts ... but it's right to consider payload as opaque.
Payload encoding/decoding is a contract between device and remote service (for understating telemetry data, command and related response).

Finally all options will be opened : body as AMQP Data or AMQP Value

I agree !

**Comment by sophokles73** [comment]
I do not see why we would need/want to support AMQP Value body sections. It only introduces an additional case we need to handle within Hono but does not provide any advantages, does it?

**Comment by ppatierno** [comment]
Why we want to support only a part of AMQP ?
If a customer wants to use Hono with AMQP it should be free to use any encoding it provides from simpler JSON, XML to AMQP type system.
I don't see any additional complexity because as we said the payload is always opaque and Hono doesn't process it ... at least in the code should check its type (Data or AMQP Value) I suppose.

In a lot of case using AMQP Value can take advantages in terms of payload size for example.
JSON and XML need always tag/attribute name and value.
With AMQP map or list you can build your structured data without specified additional metadata around it in the payload but they are pre-defined as a contract between device and service.

I mean, with JSON you could have something like this : 

{ "temperature" : 30, "humidity" : 50 }

with AMQP Value only : 

30 50

Of course it's possible even with raw Data section but using something that is strongly typed is always better (like for programming languages).

If we customize Hono too much with reduced interfaces or features it's not so good IMHO.

**Comment by sophokles73** [comment]
I do not see why you couldn't achieve the same thing using the byte representation of two integers or shorts in a Data section. In both cases the receiver needs to know the structure of the message and what the two values actually mean.

As discussed during the review of the (Telemetry API)[/eclipse/hono/wiki/Telemetry-API) in our face-to-face, we settled for allowing the payload as a Data section only (at least for the Telemetry API).
