### ISSUE TITLE
How to configure the log level of Hono

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2022]
Hi there,

we deployed Hono(1.2.2) at kubernetes cluster. 
The default log level is debug, I try to inject environment variables "**LOGGING_LEVEL_ROOT=INFO**" to container, but it didn't take effect.
So how should I control the output level of the log?

Thanks.

**Comment by sophokles73** [comment]
If you only want to decrease the logging level uniformly to INFO, then the easiest way to do it is by means of setting the container's *SPRING_PROFILES_ACTIVE* environment variable to value `prod` instead of `dev`.

**Comment by gongzhao2** [comment]
Hi sophokles73,

We want to do a performance test on Hono to verify that it supports 12000 device connections (MQTT), but I can't find the number of device connections in grafana's dashboard. 

- How should I know how many devices the MQTT adapter has connected?
- In general, how many connections can a 1c2G MQTT POD support?

**Comment by sophokles73** [comment]
Has the question regarding configuring the log level been answered? If so, please close this issue and create a separate one so that other people have a chance to find questions and corresponding answers. I would also kindly ask you to pose question regarding usage of Hono on stackoverflow using the `eclipse-hono` tag. That way, you can reach the largest audience for your questions.

**Comment by gongzhao2** [comment]
Thanks!
Got it.
