### ISSUE TITLE
Provide in Device Registry Management API a separate operation for CA Certificate Update

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#2082]
Currently Device Registry Management API provides PUT operation for the whole tenant, with this operation such parameters as: the available protocol adapters, resource limits, tracing, CA-certificates etc. can be updated on the tenant level. 

In some use cases it can be useful to have PUT operation only for specific parameters of the tenant e.g. only for update of CA-Certificate. This operation could be provided to the users who are responsible only for the management of Certificates but not for the configuration of the whole tenant.

What is your opinion regarding such feature-request?

**Comment by ctron** [comment]
I do understand you use case. However there are so many options which you could consider for the same use case. Basically you would need RBAC on a field level. And translating each field access into a specialized API call would overload the API IMHO.

I think it would be better to allow anyone who has a similar use case, to extend the server side component, allowing for additional check, and rejecting the request if your custom logic thinks that is required.

I think you would need to do that anyway, because adding a new API call would mean that the user still has the ability to update the full Tenant object. And thus the new API could only be used to make the API more permissive, but not more restrictive.

**Comment by mbaeuerle** [comment]
Following up on this, was there already a discussion about adding `PATCH` support to the device management API?
By allowing patches just on specific parts of the tenant would make verification easier. 
In this case the verification could just allow for the `trusted-ca` property to be changed rejecting changes to everything else.

**Comment by mhemmeter** [comment]
@mbaeuerle: Sounds interesting to me. From my perspective a solution that prevents complex (and therefore error prone) permission checks would be very good.

**Comment by sophokles73** [comment]
@mbaeuerle you mean defining the HTTP *PATCH* verb on the `/tenants/${tenant_id}` resource as the method to set the trust anchor(s)? What if we also want to allow enabling/disabling protocol adapters?

**Comment by alinaserg** [comment]
I think the approach proposed by @ctron could work for this use case:

> I think it would be better to allow anyone who has a similar use case, to extend the server side component, allowing for additional check, and rejecting the request if your custom logic thinks that is required.

That's why I close this issue. 
If there will be necessity for this feature from somebody else in the future, the issue can be reopened.
