### ISSUE TITLE
MongoDB implementation does not check for existing tenant

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#2131]
The current mongodb implementation does not check for an existing tenant. It allows to create devices, without checking for the existence of a tenant first.

It should however use the `TenantInformationService` to ensure that a tenant exists.

Also, many of our tests currently do not set up a tenant, before registering a device.

**Comment by kaniyan** [comment]
IMHO I don't see it as a bug. The MongoDB device registry is implemented as per the OpenAPI spec. We don't have this tenant check specified in our Device Management API spec. I guess for the same reason we don't have corresponding tests. IMHO if we like to bring this tenant check, then its better to start with the OpenAPI spec. So that we can also define the appropriate response codes for the operations. Currently if the tenant doesn't exist, the `AbstractDeviceManagementService` returns 404. But 404 is not defined as one of the response codes for many device operations. I think its better to create an issue for bringing in tenant check feature and start with the OpenAPI spec. And also the same is applicable for the credentials operations. @calohmn @ctron @dejanb @sophokles73 WDYT?

**Comment by ctron** [comment]
As mentioned in the chat, I disagree:

The spec says:

> Clients use this operation to register a new device for an existing tenant with an identifier that is generated by the registry.

The second create call misses the explicit wording on "existing", which we will fix by updated the spec.

The missing items in the spec have been addresses with: https://github.com/eclipse/hono/pull/2132

**Comment by kaniyan** [comment]
As I also wrote in the chat, I differ in opinion as the spec is inconsistent and also didn't mention what is expected if a tenant doesn't exist. With no existing tests so far and also from the discussion in #2132, I see that this check is not mandatory yet. Its good that you have raised that PR #2132 to fix the spec and include the expected response codes.

**Comment by sophokles73** [comment]
@ctron can we close this based on #2141 ?

**Comment by ctron** [comment]
> @ctron can we close this based on #2141 ?

To me it looks like this only fixes the registration, but not the credentials.

**Comment by kaniyan** [comment]
> > @ctron can we close this based on #2141 ?
> 
> To me it looks like this only fixes the registration, but not the credentials.

The `MongoDbBasedCredentialsService` extends `AbstractCredentialsManagementService` where it uses the tenant informatiomn service to check if a tenant exists or not. Hence #2141 also fixes the credentials part too.

**Comment by ctron** [comment]
> > > @ctron can we close this based on #2141 ?
> > 
> > 
> > To me it looks like this only fixes the registration, but not the credentials.
> 
> The `MongoDbBasedCredentialsService` extends `AbstractCredentialsManagementService` where it uses the tenant informatiomn service to check if a tenant exists or not. Hence #2141 also fixes the credentials part too.

Ah ok, I overlooked that, I only checked the referenced PR.

Then yes, I think we can close this.

**Comment by sophokles73** [comment]
@ctron well then, will you (close it)? ;-)
