### ISSUE TITLE
HTTP Adapter forwards wrong QoS default level as application property when sending events

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2288]

**Comment by fkaltner** [comment]
@sophokles73 May I work on this?

**Comment by sophokles73** [comment]
sure, IMHO the first step would be to add corresponding assertions to the existing integration tests in order to demonstrate the problem. Which version(s) are affected?

**Comment by fkaltner** [comment]
I added a test based on the 1.4.X branch in order to demonstrate the problem

As far as I can see, the bug was introduced with a43f572904420a004f4b21d5c247b66c24a5f023 on 2020-06-29.
So I think 1.2.x, 1.3.x and 1.4.x are affected.

To my understanding 1.5.x should not be affected as there was a code change which fixed this bug.

**Comment by sophokles73** [comment]
Based on our *support policy* we should fix this on branches 1.4.x and 1.3.x. So I guess we should have
* a PR for adding the corresponding integration test (extensions) to master in order to assert this behavior for 1.5.0 and future versions
* a PR for adding the corresponding integration test (extensions) to 1.4.x along with the fix for 1.4.x
* a PR for adding the corresponding integration test (extensions) to 1.3.x along with the fix for 1.3.x

I agree that it is desirable to fix it on 1.3.x and 1.4.x with as little code changes as possible.

**Comment by sophokles73** [comment]
@fkaltner can this be closed?

**Comment by fkaltner** [comment]
Yes, this should be fixed as discussed.
