### ISSUE TITLE
Telemetry API : latitude and longitude

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#23]
Why we are including information such latitude and longitude in the API reference implemantation ?
Are they too much related to the application domain and the related business ? Aren't they ?

**Comment by sophokles73** [comment]
We agreed to remove these properties (as well as the *sample-time* application-property) from the (Telemetry API)[/eclipse/hono/wiki/Telemetry-API] in our face-to-face meeting because we did not want to impose any particular encoding format for the geo-location, in particular with respect to our limited knowledge in the geo-loc space ...
