### ISSUE TITLE
Device Registry Management API status object uses kebab-case property

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2309]
The *status* object's *last-user* property is defined using kebab-case instead of camel-case.
This should be changed in order to be consistent with the other property names.
Since this is read-only property for informative purposes only, I think that we can change the name without breaking any provisioning processes.

**Comment by calohmn** [comment]
In #1910, the idea was to change 2 properties in the other direction, from camel-case to kebab-case (unfortunately, these `viaGroups` and `memberOf` properties are the first to appear when opening the topmost `device` object in the swagger UI).

Looking at all the properties in the `device-registry-v1.yaml` file, there are actually way more kebab-case properties (18 vs 4).
The `status` object contains the 2 kebab-case exceptions `autoProvisioned` and `autoProvisioningNotificationSent`, and in the `device` object there are the `viaGroups` and `memberOf` properties mentioned in #1910. 

Since the `autoProvisioned` and `autoProvisioningNotificationSent` were just added 2,5 weeks ago, I would rather change these to kebab-case to have a consistent style in the `status` object.

**Comment by sophokles73** [comment]
@calohmn taking another look at the OpenApi spec, I believe you are right. I have opened #2369 instead ...
