### ISSUE TITLE
AMQP Client receives "SASL handshake failed"

### ISSUE THREAD

**Issue by ArashJavan** [eclipse/hono#2315]
Hi,
I installed the hono via "cloud2edge" package, as it is described [here](https://www.eclipse.org/packages/packages/cloud2edge/tour/).

I can create "tenant" and register devices. After that I tried using the "Hono Command Line Client" to send a command to a device by using this:
`java -jar hono-cli-*-exec.jar --hono.client.host=$AMQP_NETWORK_IP --hono.client.port=15672 --hono.client.username=consumer@HONO --hono.client.password=verysecret --tenant.id=$MY_TENANT --device.id=$MY_DEVICE --spring.profiles.active=command`

But unfortunately I get an "handshake failed" exceptoin. Below you find the log-file of the amqp-adapter.
[logs-from-eclipse-hono-adapter-amqp-vertx-in-c2e-adapter-amqp-vertx-777d774b55-qfx58.txt](https://github.com/eclipse/hono/files/5581727/logs-from-eclipse-hono-adapter-amqp-vertx-in-c2e-adapter-amqp-vertx-777d774b55-qfx58.txt)
 
Any suggestion what is going wrong would be great!

Thanks!

**Comment by sophokles73** [comment]
The log file you provided indicates that an AMQP client tries to connect to the adapter but provided wrong credentials. The log also tells me that you are trying to send the command to the device by connecting to the protocol adapter. That doesn't work. You need to connect to Hono's north bound Command & Control API instead. It seems like your `AMQP_NETWORK_IP` points to the AMQP adapter service instead of the dispatch router service.

**Comment by ArashJavan** [comment]
@sophokles73 I appreciate your help! Well, really strange since I use " setCloud2EdgeEnv" script for finding out all the IPs and ports! but nevertheless I removed cloud2edge package and installed only hono. And it is working now!
Should I get the error again, I will check explicitly for the IPs and will report here, if it is a real issue and not my own bug ;)

Thanks again!
