### ISSUE TITLE
The received command message's topic missing tenant ID

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2363]
Hi, I try to send command to my device, but the message topic I received missing tenant ID, it's just a blank. like below picture.
![image](https://user-images.githubusercontent.com/66044894/101737541-fe276c00-3aff-11eb-8df0-25b865925f34.png)

Why the message.topic I received missing tenant ID, how can I add it to the topic?

Thanks in advance.

**Comment by sophokles73** [comment]
which version of Hono are you using?

**Comment by gongzhao2** [comment]
Hi,
Hono version: 1.2.3
mosquitto version: 1.6.8

**Comment by sophokles73** [comment]
You might want to refer to the [MQTT adapter user guide](https://www.eclipse.org/hono/docs/1.2/user-guide/mqtt-adapter/#command-control), which describes the adapter's behavior for different Command & Control client types. First you will need to figure out, which type matches your use case.

**Comment by gongzhao2** [comment]
I want to **receive commands with authenticated gateway**, that's why the message I received don't have tenant id.
![image](https://user-images.githubusercontent.com/66044894/101791442-7f9def00-3b3e-11eb-8506-790a655b04ef.png)
I want to know why the topic of the command received in this way does not contain tenant-id, because the authentication method of the device already contains the tenant-id?
Can I modify some configurations to make Hono return a complete topic in this way?

**Comment by sophokles73** [comment]
> Can I modify some configurations to make Hono return a complete topic in this way?

No, you can not.

**Comment by calohmn** [comment]
Since you are using an authenticated gateway, you have established the MQTT connection in the context of the tenant given in the username (DEFAULT_TENANT in your example) anyway. So, all the commands that you receive via this connection will be for devices of that particular tenant. That's why there is no need for the tenant to be in the topic to which commands are published for an authenticated gateway.

**Comment by gongzhao2** [comment]
Thanks sophokles73, calohmn.

**Comment by gongzhao2** [comment]
Hi there,
We are using lora network server of Chirpstack as our MQTT client to receive command(authenticated gateway), but the lora network server report an error "topic regex match error" because the topic hono returned is missing "tenant-ID".
![chirpstack_lns_error](https://user-images.githubusercontent.com/66044894/102176117-bdeb3380-3edb-11eb-9e8f-46d5df97ebaf.jpg)
Has the topic format returned by Hono considered the compatibility of other products?
Actually, I tested the mosquitto broker and it will return the full address of the topic.
**So I want to know if Hono will return the complete topic in the future. Is this in the plan?**

lora network server version: 3.11.0
hono version: 1.2.3

Many thanks!

**Comment by sophokles73** [comment]
I am no expert in Chirpstack's server and its capabilities but it seems to me like you are trying to configure the Chirpstack server to act as a gateway for devices connected via LoRa. As such, it looks like you have configured the Chirpstack server to connect to Hono's MQTT adapter using a set of credentials which also contain the tenant that the (LoRa) devices belong to in the username. 
You also seem to have configured a regular expression for extracting information (including the tenant ID) from the topic name of downlink messages. If this true, then you do not need to extract the tenant ID from the topic name because the tenant ID is the same for all devices and is the same as the tenant ID that you have configured in the MQTT client credentials.

Can you post the regex that you have configured?

**Comment by gongzhao2** [comment]
Hi，
I am also not familiar with Chirpstack's server, We just use it. This regex seems embed in Chirpstack server, I can't configure it. The only thing I can configure is upstream and downlink topic.
below picture roughly describe the data flow.
![image](https://user-images.githubusercontent.com/66044894/102293731-a31fca00-3f82-11eb-99d2-4a639ad2720d.png)
The problems is lora server of Chirpstack can't accept the topic returned by Hono. More details will need some time for in-depth research.
Anyway, I am not sure which topic format is more compatible. but if the complete topic is more compatible with other products, Is there a plan for Hono to implement it?

**Comment by sophokles73** [comment]
> The only thing I can configure is upstream and downlink topic.

And what have you configured them to?

**Comment by sophokles73** [comment]
Based on the [Chirpstack application server documentation](https://www.chirpstack.io/application-server/integrations/mqtt/) that I found, what you are trying to do seems not to be possible at all. That is because Chirpstack's MQTT integration requires the component that should receive the data to *subscribe* to a topic on the Chirpstack MQTT server. Hono's MQTT protocol adapter cannot do that because it acts as an MQTT server only itself.
Let me know if you are using a different system setup and I am therefore mistaken.

**Comment by gongzhao2** [comment]
Hi,
We configure below parameters to make chirpstack publich message to hono mqtt adapter:
refer from this [documentation](https://www.chirpstack.io/application-server/install/config/)
- event_topic_template="telemetry/tenant-id/{{ .DevEUI }}"
- command_topic_template="telemetry/tenant-id/{{ .DevEUI }}/req/#"
- server="tcp://hono-mqtt-adapter:1883"
- username="..."
- password="..."

So that Chirpstack take hono mqtt adapter as its mqtt server.
The current situation is Chirpstack can publish message to hono, but won't accept the command from hono due to the topic format.

**Comment by sophokles73** [comment]
Are you running your own instance of the Chirpstack application server? Are you running it for a single tenant only?

**Comment by gongzhao2** [comment]
Actually, our partner is in charge of Chirpstack, I think they build their own instance of Chirpstack in their environment.
Does the single or multiple tenant influence this issue?

**Comment by sophokles73** [comment]
> Does the single or multiple tenant influence this issue?

I am not sure about the inner workings of Chirpstack Application server. But if there is only a single tenant (= `{{ .ApplicationID }}` ?), then the command_topic_template could probably simply be changed to `command//{{ .DevEUI }}/req/#"` or `command/+/{{ .DevEUI }}/req/#"`

**Comment by gongzhao2** [comment]
Yeah, We have tried the above two topic formats
- command/+/{{ .DevEUI }}/req/#
- command/tenant-id/{{ .DevEUI }}/req/#

both of them report the same "REGEX" error.

**Comment by gongzhao2** [comment]
I think the problem is Chirpstack can't accept the blank topic, this is the root cause.
So we plan to use mqtt bridge to forward the message to Chirpstack.

**Comment by sophokles73** [comment]
I had actually proposed to use
`command//{{ .DevEUI }}/req/#`
i.e. without the `+` sign ...

**Comment by sophokles73** [comment]
But I see your point. The MQTT adapter currently does not include the tenant ID in the topic in order to reduce message size. However, I can imagine that we make this behavior configurable at the tenant level, so that for certain tenants the tenant ID is included in the topic name.

**Comment by gongzhao2** [comment]
Yeah, I think it is a good idea to make this configurable to meet the needs of different scenarios.

**Comment by gongzhao2** [comment]
Is this a big change for Hono to implement this feature? need long time to implement it?
We currently use mqtt bridge method to circumvent this issue.

**Comment by sophokles73** [comment]
No, this doesn't look like a big thing.

However, you seem to be running on a version of Hono (1.2.x) which the Hono open source project is not able to support anymore. We provide fixes for the two most recent minor versions. We have just released Hono 1.5.0, so you should upgrade to 1.4.4 or 1.5.0 in order to take advantage of service releases.

**Comment by sophokles73** [comment]
closed via #2374
