### ISSUE TITLE
CoAP - Event Queue Full - Response Code 4.00 (Bad Request)

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#2418]
When sending event's too fast, the event queue gets full. Then the client receives

> 4.00 - AMQ229102: Address "event/<my_tenant>" is full.

Is that by intention? 
Should it be adapted to 5.03?

**Comment by sophokles73** [comment]
Based on the response code (4.00) I'd say that this is a bug since this is clearly not the client's fault and I agree that this should rather result in a 5.03 being returned to the device.

**Comment by calohmn** [comment]
I guess at some point `.recover(thr -> Future.failedFuture(StatusCodeMapper.toServerError(thr)))` needs to be added to translate the client error (like [here](https://github.com/eclipse/hono/pull/2352/files#diff-1f6a8df336aae67d760da530cc0acc3cd6816c7f8f85647592772f738dc2dccbR94)).

**Comment by calohmn** [comment]
It looks to me as if Artemis has sent a "rejected" disposition here, which will get mapped to a "400 - Bad request" here:
https://github.com/eclipse/hono/blob/cb3fc07228b2c13ebcfcd066c1c265bef16113f3/client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java#L315-L319

The general case of translating a "rejected" disposition to a client error still seems valid to me (message got rejected because the client sent an invalid message).
The specific error here however should probably get special treatment. Of course doing product-specific error string matching doesn't look pretty, but I guess matching the Artemis-specific (?) error code "AMQ229102" would be ok here, since both usage of Artemis and this specific error should be quite common.

**Comment by boaks** [comment]
I would prefer to adapt the HTTP_BAD_REQUEST in case of the AMQ-code for full event-queue.
For me this is similar to the telemetry case 5.03, when too many messages are send in a time period.

**Comment by sophokles73** [comment]
@calohmn I would rather not check the error's *description* but the error's *condition* instead. Do you have a setup where you can reproduce the issue? I am asking because we will need to find out, which condition is being set by Artemis in this case. I would guess that it is `amqp:resource-limit-exceeded` but we will need to be sure ...

**Comment by calohmn** [comment]
@sophokles73 Very good point! I haven't been able to reproduce it easily yet (was trying to use the integration tests for that).
But this Artemis test strongly suggests the error condition can be used:
https://github.com/apache/activemq-artemis/blob/3541ebf2181aa8383942d039564fc8332b639cdc/tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFlowControlTest.java#L238

**Comment by sophokles73** [comment]
Yes, might experiments suggest the same ...

**Comment by sophokles73** [comment]
This also affects the other protocol adapters because the handling of the rejected disposition is not device protocol specific.

**Comment by calohmn** [comment]
I think in this case here a localized ServerErrorException should be used, as introduced in #2185.

**Comment by sophokles73** [comment]
@calohmn what for? Isn't a 5.03 response adequately describing the issue, i.e. *wait a little and then try again*?

**Comment by calohmn** [comment]
@sophokles73 When knowing that the error has a "resource-limit-exceeded" cause, the user could possibly update the used messaging service plan, increasing the quota, so that the error soon doesn't arise any more.

**Comment by boaks** [comment]
This message is sent to the device. Therefore the device should have a hint, what to do. 5.03 is that hint, 4.00 not.
To inform the "user" to act may be a different action. I guess, this should be done by e-mail.

**Comment by sophokles73** [comment]
@boaks I think we all agree that we want to return a 503 in this case. The only question is whether we want to include additional information about the problem in the response body in this case.
@calohmn I see your point but am a little hesitant to expose (potentially) internal technical details for that purpose. I am not sure if a user correctly connects the dots from the description that an address space is full to the plan that needs to be upgraded. In particular since this will only be relevant if the situation arises frequently. If you have a good suggestion for such additional information then I am more than willing to include a dedicated exception for it ...

**Comment by calohmn** [comment]
@sophokles73 I think we can at least use the following message:
````
SERVER_ERROR_MESSAGE_RESOURCE_LIMIT_EXCEEDED=consumer rejected the message because a resource limit was exceeded
````
(entry for `ServiceInvocationException_messages.properties`)

A bit more specific would be: `consumer rejected the message because a resource limit was exceeded, possibly a (tenant-specific) queue size limit`

In any case, I think an error description would be helpful here. It could be added to an FAQ page ("what to do if this error occurs") of a service using Hono and could help support staff answering corresponding support questions more quickly.
