### ISSUE TITLE
[#8] Duplicate logic for parsing of Kafka headers

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2460]
I found that the classes `RecordUtil` and `KafkaMessageHelper` implement the same use case: getting and decoding Kafka headers. It would be good to have this implemented only once.

**Comment by b-abel** [comment]
The main difference I found is, that `RecordUtil` does not return a value if it found another header with the same key while `KafkaMessageHelper` always returns the first header with a matching key. (On the producer-side we should anyways always ensure that we cannot have duplicate keys).

**Comment by kaniyan** [comment]
It is better to avoid duplication and reuse the code. IMHO `KafkaMessageHelper` is already being used for the `telemetry/event` side and it could also be extended to process `commands` too.

**Comment by calohmn** [comment]
How about renaming `KafkaMessageHelper` to `RecordHelper` then (`Message` is more of an AMQP term) and adding the duplicate header check?

**Comment by b-abel** [comment]
> How about renaming `KafkaMessageHelper` to `RecordHelper` then (`Message` is more of an AMQP term) 

I'm fine with that.

> and adding the duplicate header check?

My implementation does not enforce this on purpose. I would rather accept a message with a duplicate key in the header than dropping it as there is no way to inform the initial sender about it. We should better spend our energy on the producer-side and implement producer in a way that prevents duplicate header keys and clearly state that requirement in the command API.

**Comment by calohmn** [comment]
> I would rather accept a message with a duplicate key in the header 

What if the producer is the northbound application (sending commands and not using our Kafka client classes)? I would rather be more strict here than work with the potentially wrong header value. And about informing the initial sender: this is a problem we face also concerning other ways in which the record might be invalid (missing headers or invalid values). So, I would rather not make a special case for duplicate headers here. 
In order to inform the sender, an idea would be to introduce an error topic to which the northbound application can subscribe and get informed about such errors.

**Comment by kaniyan** [comment]
@b-abel  @calohmn We already deal with handling of multiple headers having the same key in Hono. In case of HTTP headers, we take the first header value. We could apply the same here in case of kafka headers too and keep it uniform. IMHO what is important, is to clearly document the behavior in the specifications.

**Comment by calohmn** [comment]
Well, taking the first header and not causing an error is still not my preference, but at least there's some consistency to it. So, ok.
Interestingly, the Kafka `Headers` interface only has a `lastHeader` method for getting a single header.
