### ISSUE TITLE
Device Registry: Error responses do not comply with the specification

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2471]
The current device registry implementations _(File, JDBC and MongoDB)_  return error responses that do not comply with the below _schema_ as defined by the [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/).

```
      Error:
         type: object
         additionalProperties: true
         required:
            - error
         properties:
            "error":
               type: string
               description: A human readable error message of what went wrong.
```

Currently I see two patterns, in case of error responses being returned by the device registries.

1. The first pattern is an error response of type `String`. 
     Example: While trying to register a tenant with invalid payload json, then the response status code is `400 Bad Request`  
     with an error response as `request does not contain a valid Tenant object`

2. The second pattern is that the error response is simply _null_. 
     Example: Try to update an existing information with an invalid resource version. Then the returned response status code is  `412 Precondition Failed` with _null_ as the error response.

**Comment by sophokles73** [comment]
This should probably also be addresses in context of #2639

**Comment by sophokles73** [comment]
I have taken a closer look to how this could/needs to be changed in Hono. The underlying issue here seems to be that the `TenantManagementService`, `DeviceManagementService` and `CredentialsManagementService` interfaces' methods also return a succeeded future in an (expected) error case. The succeeded future, however, provides no means to convey an error message because the future's type is `Result<T>` with `T` being the type of payload to return in the response body in case of a successful invocation. However, unexpected errors still result a failed future being returned, which makes error handling code hard to read and implement.

FMPOV the method signatures (and implementations) should be changed to *only* return succeeded futures in case of successful invocation with a status code of [200, 400) and return a failed future in all other cases. For expected errors, the future can then be failed with a `ServiceInvocationException`, analogously to how we already do it in the clients.

However, this will result in quite some work as the current behavior is manifested across many layers and throughout all registry implementations.

@calohmn @kaniyan @dejanb @ctron WDYT?

**Comment by kaniyan** [comment]
> FMPOV the method signatures (and implementations) should be changed to _only_ return succeeded futures in case of successful invocation with a status code of [200, 400) and return a failed future in all other cases. For expected errors, the future can then be failed with a `ServiceInvocationException`, analogously to how we already do it in the clients.

Also `TenantService`, `CredentialsService` and `RegistrationService` follows the same pattern. Eventhough the chages in those classes are not required in relation with this issue, this would lead to double standards. At some point of time, it is also good to change them and have a single standard.

> However, this will result in quite some work as the current behavior is manifested across many layers and throughout all registry implementations.


In consideration of the issue #2639, FMPOV failing with a _current version_ of `ServiceInvocationException`  alone may not be sufficient.  Another alternative that doesn't require so many layers to be changed would be to encapsulate all the necessary error information (like error code, message, description etc.) in an object of a new class type (eg.  `ErrorInfo`, `ErrorResponse`). The `Result` class can have a new field of type `ErrorInfo` and related helper methods to _access_ and _set_ error information. 
`AbstractDelegatingRegistryHttpEndpoint.writeResponse()` can make use of this error information to set the _http response_ in case of error.

**Comment by kaniyan** [comment]
> However, it simply doesn't feel right to me to convey errors in succeeded futures.

The operation result is designed to contain both success and erroneous outcomes. Since these methods have return type `Future<OperationResult<>>`, IMHO it doesn't make that awkward but it is not straight forward if any one look into the code to understand.

 > In particular, if there still are _some_ (unexpected) errors that indeed get conveyed in failed futures. 

I agree in case of unexpected error being conveyed in failed futures. I also like the other approach which makes things straight forward. Even though many layers have to be touched and  I think that's the way to go.

**Comment by sophokles73** [comment]
@calohmn any thoughts?

**Comment by calohmn** [comment]
I always found it rather confusing that Hono API methods with a `Future<OperationResult<T>>` or `Future<Result<T>>` return value would return a succeeded Future for some failures and a failed Future for others.
(Also usage of the `empty` method as in `Future.succeededFuture(OperationResult.empty(HttpURLConnection.HTTP_BAD_REQUEST))` strikes me as a bit odd.)

I also found the difference in this regard between client and service interfacing quite striking and somewhat unintuitive.
E.g. `TenantService` with `Future<TenantResult<JsonObject>> get(String tenantId)`
vs.  `TenantClient` with `Future<TenantObject> get(String tenantId, SpanContext context)`.

One thing to consider before deciding on such a change would be whether there are some extra `OperationResult` fields filled in error cases, besides the error status. 
Theoretically, a candidate would be the `cacheDirective` field, for failed results that may nonetheless be cached. But that is something that isn't done currently in Hono, and one could imagine adding a corresponding field to the `ServiceInvocationException` class, if ever the need for that arises. 
In general, an OperationResult for a failed operation only gets created with the status flag at the moment. 

So, I think it would be a good thing to consistently only return failed futures in case of invocation failures.
It looks like quite a big change, though.

**Comment by ctron** [comment]
I think in the Java world, you always need to deal with unexpected Exceptions. So one needs to deal with that in any case.

However, I also think that one can do better in expected errors. Like @calohmn mentioned, there may be additional information that needs to be carried. That could also be put into an Exception, but that feels odd to me as well. As it isn't an "Exception", it may be a regular case.

My proposal would be to return [200, 500) as part of the result. 5xx is a server error, and that can be carried by an Exception. But I have no strong opinion here.

**Comment by sophokles73** [comment]
> I think in the Java world, you always need to deal with unexpected Exceptions. So one needs to deal with that in any case.

Of course, but in our case any unexpected errors already result in failed futures which we already handle. The issue here FMPOV is that we need to duplicate error handling code.

>  there may be additional information that needs to be carried. That could also be put into an Exception, but that feels odd to me as well. As it isn't an "Exception", it may be a regular case.

I currently do not see any *additional information* that we would want to include in case of invocations resulting in an error status code. The *OperationResult.empty()* method does not include a cache directive in the response so FMPOV there is no issue at hand. Event if we would want to include a cache directive, I wouldn't have any problem with including it in a corresponding exception. But again, there doesn't seem to be any need to do so ...

> My proposal would be to return [200, 500) as part of the result. 5xx is a server error, and that can be carried by an Exception. But I have no strong opinion here.

FMPOV that would not allow us to improve the (confusing) error handling code that we currently have, would it?

BTW on the client side we already use the proposed approach, i.e. a future is succeeded if the invocation was successful (in case of the registry if the response contained a status in [200,300)) and a failed future in all other cases ...
