### ISSUE TITLE
Refactor client module so that it does not assume a certain component as client

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2540]
See https://github.com/eclipse/hono/pull/2534#pullrequestreview-611886500

I think it makes also sense to convert `AdapterConfigurationSupport` to an interface, as well as `ProtocolAdapterProperties`(only the part which is actually required). This would also enable us to give them proper names illustrating what is actually required for configuration for the client.

NB: This issue should not be started before the Kafka migration itself is completed (at the time of this writing this means not before 1.7.0 is released) as we might run into merge hell otherwise...

**Comment by sophokles73** [comment]
An obvious candidate seems to be to factor out the telemetry client into a separate module because the device registry for example uses requires it to publish events. The Command Router, on the other hand, also needs to consume commands and needs to query the registry services but is (obviously) not a protocol adapter. We could therefore simply use a less opinionated name for the *adapter* client module or we could factor out the command and registry clients into dedicated modules as well.

WDYT? @calohmn @fkaltner @kaniyan

**Comment by fkaltner** [comment]
I think the main problem was already addressed by bccad71b6737e62d6c6865136b0a413a0abdc4b9 making the reference to ProtocolAdapterProperties obsolete. But the separate modules do also make sense 👍 as the naming of the imports still was a bit odd...

**Comment by sophokles73** [comment]
@calohmn @kaniyan I do have two more PRs on hold for factoring out the C&C and the Device Registry client(s) into separate modules. FMPOV we should go all the way now and resolve the (still) existing *adapter* client module into dedicated *registry* and *command* client modules as well. WDYT?

**Comment by calohmn** [comment]
@sophokles73 Ok, good. There will probably be a conflict with #2711 - I can adapt that PR after your PR got merged then.

**Comment by kaniyan** [comment]
> resolve the (still) existing _adapter_ client module into dedicated _registry_ and _command_ client modules as well.

+1

**Comment by sophokles73** [comment]
closed via #2721
