### ISSUE TITLE
Command responses need to be forwarded using correct messaging infrastructure

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2592]
The messaging infrastructure to be used by devices of a tenant can potentially be changed during runtime by updating the tenant configuration. The following might happen:
1. a protocol adapter receives a command request via AMQP
1. the adapter sends the command request to the device
1. the preference is changed from AMQP to Kafka
1. the device sends its command response to the adapter
1. the adapter determines the messaging infrastructure to be used for devices of the tenant as Kafka and forwards the command response to the Kafka broker
1. the downstream application which had sent the request via AMQP never gets the response

**Comment by sophokles73** [comment]
@calohmn @b-abel @kaniyan Can you confirm that this might be an issue?

**Comment by calohmn** [comment]
I think whether we should see this as an issue depends on the kinds of requirements we associate with changing the messaging network preference from AMQP to Kafka.

I think one could argue that as soon as this switch is done, the northbound application has to have the corresponding Kafka consumers in place and the Kafka topics for the tenant must exist. If that is the case, the northbound application can receive the command response message. Of course the application has to be able to correlate the response message to the original command message (given the correlation-id header of the command response record), which might be a challenge depending on the implementation.

In order to send the command response via AMQP in the above scenario, we would first have to encode the information about which messaging system to be used in the request-id that is part of the command sent to the device. When getting that request-id as part of the command-response in the adapter, the corresponding messaging system would be used.
But what if the command-response comes a long time of the command was sent - when the northbound application has already closed the AMQP command response receiver?

I would prefer, if we could require the northbound application to be able to already receive the Kafka-based command response - or the northbound application has to send the command again, that time via Kafka.

**Comment by b-abel** [comment]
> I would prefer, if we could require the northbound application to be able to already receive the Kafka-based command response - or the northbound application has to send the command again, that time via Kafka.

I agree.
Does Hono have a hard guarantee that every command response will be delivered? FMPOV, the messaging infrastructure to be used should not be changed regularly, but at most once per tenant. Therefore, I would like to keep the logic that supports such a one-time event to an absolute minimum.

**Comment by sophokles73** [comment]
This is all fine as long as we make sure that an application (and Ditto in particular) has a chance to detect the problem and act accordingly.

**Comment by calohmn** [comment]
As discussed in the Hono community call:
The preferred solution here is to send the command response using the same messaging network that the command was received from. The used messaging system therefore has to be encoded in the request id contained in the command forwarded to the device.

(This relates to #2736, allowing commands to be received from all configured messaging networks.)

**Comment by calohmn** [comment]
Fixed via 4b3afcd8a04dd217272c1e3bbdf09307957372a2 (#2753).
