### ISSUE TITLE
Support authentication of devices using MQTT username/password

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#261]
The MQTT Adapter should support authentication of devices by means of verifying credentials provided in the Username/Password fields of an MQTT CONNECT packet.

**Comment by sysexcontrol** [comment]
I started on that, can you please assign this to me? Thanks.

**Comment by sysexcontrol** [comment]
Remark: this will not revalidate the credentials after certain time during open MQTT sessions, as described in #293.

**Comment by sysexcontrol** [comment]
The implementation of "username/password" authentication for the MQTT adapter is fully provided in the master branch.

Since this made problems with the topic structure obvious, a discussion and proposal to introduce a new topic structure was made on the developer mailing list, thus this issue is kept open currently.

**Comment by sophokles73** [comment]
fixed in ddf190d0650d8b60ccb176b133ae98e0eb6db58f
