### ISSUE TITLE
Add meaningful readiness and liveness checks to Hono Messaging

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#262]

**Comment by sophokles73** [comment]
IMHO a meaningful check should do the following:
* check if we currently have a usable connection do the downstream AMQP 1.0 Messaging Network (i.e. Dispatch Router)
* check if we are able to connect to Auth Server

WDYT @ppatierno @dejanb @sysexcontrol @pellmann ?

**Comment by sysexcontrol** [comment]
FMPOV these 2 points are probably the most important ones.
How about (not exactly as important) integrating the metrics reporting capability - if configured - to the health check?

E.g. like:
- if Hono Messaging could not report to the influxdb (exc caught during attempt) this would result in an unhealthy state
- if it can report again the next time, this would flip back to healthy
- maybe this should be configurable, so that it can be decided if metrics should be part of health-check or not. Or there is more than only "healthy/unhealthy", e.g. like "green/yellow/red" with metrics mapped to yellow.

WDYT?

**Comment by sophokles73** [comment]
Well, the capability to report metrics does not per se prevent the component from fulfilling its purpose from a client's perspective. I therefore tend to omit this check for now. I am also not sure if we can actually *hook into* the reporting process and e.g. register an exception listener ...

**Comment by sysexcontrol** [comment]
+1.
More like a possible future improvement, since for prod environments it may be quite important that the metrics are working.

**Comment by sophokles73** [comment]
fixed in 2e7f90b3e1fda193d4746c3debdb36120e63b707
