### ISSUE TITLE
custom adapter ambiguities

### ISSUE THREAD

**Issue by mrclbrchr** [eclipse/hono#2672]
Hello everbody,

currenty i try to find out how to use a custom adapter. Beside the custom http adapter, i cant find something directly referring to this question in the documentation. I just found the example where a bluetooth device is connected via a gateway. Is this whats meant to be "a simple mechanism to add custom protocol adapters" or is there some other solution that i just didnt found out yet?

Im thankful for every response :)

**Comment by sophokles73** [comment]
Maybe you can start out with describing what you want to do. We can then determine if a *custom protocol adapter* is the way to go or whether a [protocol gateway](https://www.eclipse.org/hono/docs/concepts/connecting-devices/#connecting-via-a-protocol-gateway) would be more appropriate.

**Comment by mrclbrchr** [comment]
Finding out how to use a custom adapter is really what i want to do. My purpose is to find out how hono is working and if its suitable for my needs. So i want to test things like these.

**Comment by sophokles73** [comment]
The [Custom HTTP Adapter Developer Guide](https://www.eclipse.org/hono/docs/dev-guide/custom_http_adapter/) is kind of outdated as we mostly encourage people to use one of the standard adapters or, if not possible, to implement a protocol gateway as indicated above, instead of implementing a protocol adapter. The reason for that is that custom protocol adapters are expected to *behave* in the same way as the standard adapters and need to have access to Hono's registry APIs which is not always desirable in production environments where the *custom* adapter is being provided by a customer.

You might want to take a look at https://www.eclipse.org/hono/docs/concepts/connecting-devices/ for an overview of options.
There is an example protocol gateway in the `examples/protocol-gateway-example` folder which you can use for reference. In any case, I believe it would be much easier to determine which approach would be the most appropriate one if you would share some information about your use case at hand.

**Comment by mrclbrchr** [comment]
Thanks for your help so far. I got it right that in general its recommended to use a gateaway, no matter if it is a device or protocol gateway? Im just wondering because i took a look at the https://www.eclipse.org/hono/docs/concepts/connecting-devices/ article, and even there a custom protocol isnt mentioned.

Im not sure if it is the best example for a use case, but it could be one for me. Lets say i have some sensoric connected via LoRaWAN and want to integrate it into hono, what would be your approach to do this?

**Comment by mrclbrchr** [comment]
Thank you, earlier on i wanted to use Gitter, but i was a little bit confused because "This application will be able to read your organization, team membership, and private project boards.", and that seemed a little bit scary to me as i dont want to give access to my or my organitation repo if i only want to chat.
