### ISSUE TITLE
Add possibility for encrypting PSK keys in device registry

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#2717]
In the (MongoDB) device registry all of the credential types except for PSKs are hashed for security reasons.
PSKs which are used for CoAP devices however cannot be hashed because of their very nature.
To store such secrets more securely I propose to add the possibility for encrypting these secrets.

This could be achieved by providing a configurable crypt key which is used for encrypting and decrypting the secrets inside the device registry.

**Comment by sophokles73** [comment]
Mongo DB seems to support [application (field) level encryption](https://docs.mongodb.com/manual/core/security-client-side-encryption/). Is that what you have in mind?

**Comment by mbaeuerle** [comment]
@sophokles73 yes it looks like this MongoDB encryption feature is what I had in mind!

**Comment by sophokles73** [comment]
I took a more thorough look at Mongo DB's application level encryption functionality. It seems that in order to use it, the application needs to have access to the (raw) Mongo DB Java driver in version 3.12.0+. The vert.x MongoClient used by the registry, however, is a wrapper around the 3.10.1 driver only. We could test if vert.x also works with the 3.12.0 driver but that would put us *off the trodden path*. We might therefore want to apply a custom strategy for encrypting/decrypting the *key* field content as part of the registry's `MongoDbBasedCredentialsDao` instead.
