### ISSUE TITLE
Enhance failure notifications with header from original command

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#2846]
We want to use the recently added [failure notifications](https://www.eclipse.org/hono/docs/api/command-and-control-kafka/#send-a-requestresponse-command) in Eclipse Ditto to provide meaningful error responses to live messages (commands in Hono speak) sent to a device via Hono. However, when receiving such failure notifications, we do not have enough context to build a response that the original sender understands properly. One solution could be to add the required information to the command (e.g. a defined header) and Hono adds the header again to the failure notification when sending it back. What do you think?

**Comment by calohmn** [comment]
I could imagine defining an additional, optional header for the command message: `delivery-failure-notification-metadata`.
Such a header of an incoming command message will be adopted for the command response message created in case of a delivery failure. In case of a successful delivery, this header won't be used, i.e. it isn't delivered to the device.

If there is a need to adopt multiple information items, one could use a JSON string as value here.
Alternatively, we could also support a header pattern like `delivery-failure-notification-header*`, so that Ditto could set
`delivery-failure-notification-header-item1`, `delivery-failure-notification-header-item2` headers for example.
I think I would prefer the single header option (and optional usage of a JSON value) though.

**Comment by dguggemos** [comment]
Using a prefix was also the first approach that came to our minds. We wouldn't have to care about encoding some characters then. But using a single header and encoding multiple values would also work for us.

**Comment by calohmn** [comment]
Created  #2859 for this. I've chosen to define `delivery-failure-notification-metadata` as a header *prefix*, meaning one can choose between using a single such header with a JSON value or multiple headers with plain string values.
