### ISSUE TITLE
Update documentation theme

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2874]
The [Hugo theme Learn](https://github.com/matcornic/hugo-theme-learn) used for Hono's documentation seems to be dead (latest release in [June 2020](https://github.com/matcornic/hugo-theme-learn/releases))  and has therefore been forked. The fork [Hugo Relearn Theme](https://github.com/McShelby/hugo-theme-relearn) is pretty active and releases frequently. I suggest that the next time the theme of the documentation is to be updated to consider switching to Relearn.

**Comment by calohmn** [comment]
I have to say this version "selector" change was one of the first things that I noticed. The tiny icons there offer no meaning for me. So, just seeing the "stable (1.12)" link there (instead of the combo box with the "Version" title) offers no clear indication to me that I can switch the version there. Changing the link text to "Hono version 1.12 (stable)" would be a bit better in my view.

**Comment by sophokles73** [comment]
@calohmn so I take it that you are strongly in favor of re-applying the customization that we had before the migration, right?

**Comment by calohmn** [comment]
Maybe the icon can be changed by overriding the style like this (using a [caret-down](https://fontawesome.com/icons/caret-down?s=solid) icon):
```
.fa-language::before {
  content: "\f0d7";
}
```
(Haven't been able to really test it - I don't see the version selector when testing locally.)

That together with the change of the link text ("Hono version 1.12 (stable)") would make it ok, I think.

**Comment by sophokles73** [comment]
@calohmn I have replaced the icon with a code branch using CSS magic as proposed by you. WDYT?

**Comment by calohmn** [comment]
@sophokles73 Looking good now.

**Comment by sophokles73** [comment]
closed via https://github.com/eclipse/hono/commit/0ab4b6bd6ca6a505c5af4d8e333dfdc98575ad7d
