### ISSUE TITLE
Registration assertion should not be propagated to consumers

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#292]
The AMQP messages produced by protocol adapters for telemetry/event data currently contain the originating device's registration assertion in the message's *application-properties* as defined by the *Telemetry* and *Event* APIs. However, *application-properties* are required to be propagated by any intermediary AMQP node, which means that we forward the assertion from Hono Messaging to the AMQP Messaging Network and from there to the final consumer of the data. This seems to be a waste of bandwidth since the assertions are only required and processed by Hono Messaging. It therefore seems to make sense to move the registration assertion to the AMQP *delivery-annotations* and have Hono Messaging simply remove it when forwarding a telemetry/event message downstream.

**Comment by ppatierno** [comment]
Totally agree on that, using a delivery-annotations makes much more sense to me. It's used until the first hop from the adapter (so the Hono Messaging) and then removed not propagating it downstream.

**Comment by sophokles73** [comment]
As good as the idea sounds, it has the usual pitfall of being compatible with JMS clients.
Currently, the AMQP JMS Mapping spec does not provide for means of mapping any properties from JMS to an AMQP message's *delivery-annotations* :-(

So, for the time being, we could argue that Hono Messaging is *not* merely forwarding messages but is actually *processing* messages received from protocol adapters. This way, we would not be subject to the AMQP spec requiring intermediary nodes to leave *application-properties* untouched and we could instead remove the assertion from the message before sending it downstream.

@pellmann @ppatierno WDYT?

**Comment by pellmann** [comment]
I think it would be okay, to define it that way - since it is our defined API and we could remove some application properties in one defined processing step. 

But I do think the compatibility with JMS is mostly important on the solution/application side - the consumers. I do not think that adapters with JMS are a big deal. So it might not be a problem if Hono Messaging removes the delivery-annotation. Consumers with JMS will not notice and never need to handle with delivery-annotations. 

@sophokles73, @ppatierno  - do you think, JMS compatibility on the adapter-side is needed?

**Comment by sophokles73** [comment]
For the time being, we are still using an application property for conveying the assertion from adapters to Hono Messaging but we are removing it before the messages are sent downstream.

see e29d55b93ecb168b5ea761f0f3ad137a3b42aee6
