### ISSUE TITLE
MQTT adapter should close client connection when corresponding tenant/device is deleted/disabled

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#293]
The device authentication for MQTT is verifying the credentials during the CONNECT message to not let devices with invalid username/password combination build up a MQTT connection at all.

While this is necessary, it still allows for devices to keep a connection open and use it for an arbitrary time until it is closed.
Credentials that were revoked or deleted in the meantime do not lead to a disconnect.

Thus open MQTT connections should be checked at certain time intervals again if the credentials are still valid. The time period should be configurable in the MQTT adapter (since it seems to mainly affect the MQTT protocol).

**Comment by ppatierno** [comment]
I have the following comment on this ..
On the other side of the MQTT adapter we have AMQP 1.0 so we should be able to push something that happen (i.e. credentials revoked, device disabled, ...) to the adapter in order to disconnect the client. Why we should use a polling in an HTTP way ?

**Comment by sophokles73** [comment]
good point

thinking a little about options for implementing this: would you rather have the Device Registration service *broadcast* device lifecycle events to all connected clients (protocol adapters) or to try to send the events to the adapter that the device is connected to only?
The former seems to be much simpler to implement whereas the latter would reduce unnecessary traffic. But we might be talking about very small numbers of events anyway so that would probably not be an issue.

**Comment by ppatierno** [comment]
@sophokles73 Yes I like the first way, the second seems to be over complicated for such use case.
We should define one or more address for such events. An interested Hono client should attach as receiver on that for being pushed info and behaving in the correct way that for the adapter means disconnecting the client.

**Comment by alinaserg** [comment]
I want to start the discussion of the above described issue again and if it will be possible try to find the solution for MQTT protocol adapter as well as for AMQP adapter.

As far as I know the behaviour of MQTT adapter was changed in the mean time with [#876](https://github.com/eclipse/hono/issues/876)). Meaning if device tries to communicate with MQTT adapter after credentials were revoked or device was deleted, the error will occur and connection to the device will be closed.

In the GitHub Issue [#2064](https://github.com/eclipse/hono/issues/2064) there's a discussion to extend the logic in MQTT adapter and in case of hono internal errors (limits exceeding) don't close the connection, but send PUBACK to the device and publish error to the device on a specific error topic.

In case of AMQP adapter the connection will stay open in case of any errors, even if the device was deleted or credentials were revoked.

I think in cases, when:

* Device is deleted or disabled;
* Credentials are revoked;
* Protocol adapter is disabled;
* Tenant doesn't exist any more.

there's no necessity to wait till device initiates communication with protocol adapter, to close the connection, but the connection to such devices can be actively discontinued by AMQP or MQTT protocol adapter to not keep connection open for disabled devices.

@calohmn @sophokles73 @kaniyan What is your opinion to closing the connection, taking into account upcoming changes for MQTT adapter.

**Comment by sophokles73** [comment]
So far, the protocol adapters do not become aware of changes to the device's registration status and/or credentials because there is no notification mechanism in place. FMPOV the mechanism discussed above might be used for the purpose proposed by @alinaserg. However, I do not think that there is any particular relation with #2064 because this will not prevent devices from
1. trying to connect to an adapter with wrong credentials (and being rejected) and
2. trying to send messages on behalf of non-existing devices.

The first case is already properly handled, i.e. the adapter will not establish the connection with the device. The handling of the second case is the subject of #2064.

In any case, being able to actively disconnect devices as a result of a change in their registration status and/or credentials seems to be a good idea and since we already made the device registry send an (auto-)provisioning event, we could extend that behavior to include events indicating changes to other properties as well ...

**Comment by calohmn** [comment]
@sophokles73 I think the relation to #2064 is here, that as long as we don't have the added notification mechanism from the device registry to the protocol adapters, the AMQP/MQTT device connections would at least get closed in the above mentioned cases when the device tries to send another telemetry/event message. For MQTT, this means preserving the existing disconnect behaviour explicitly for these cases in the changes for #2064. For AMQP, this explicit closing of the connection in case of such errors still needs to be done. Even after the device registry notifications are in place, having such a MQTT/AMQP adapter behaviour would still be useful in case device registry notifications get lost (e.g. due to temporary connection issues between Hono components and the AMQP messaging network).

> since we already made the device registry send an (auto-)provisioning event, we could extend that behavior to include events indicating changes to other properties as well ...

AFAIK, these (auto-)provisioning event are only targeted at northbound applications, so we would need to use a different type of events here.
FMPOV, we could let the device registry send the (e.g. "device deleted") notification messages on some kind of `internal_event` address to the AMQP messaging network. Protocol adapters would create receiver links on that address and the AMQP messaging network would need to apply multicast semantics to forwarding messages on that address.

**Comment by sophokles73** [comment]
> AFAIK, these (auto-)provisioning event are only targeted at northbound applications, so we would need to use a different type of events here.

FMPOV one of the biggest advantages of using events is that you do not need to make assumptions regarding who will receive and process the events. You simply publish an event in order to indicate that something specific has happened. AFAIC we can therefore very well use the same event type, regardless of who the consumer of the event will be.

> FMPOV, we could let the device registry send the (e.g. "device deleted") notification messages on some kind of internal_event address to the AMQP messaging network. Protocol adapters would create receiver links on that address and the AMQP messaging network would need to apply multicast semantics to forwarding messages on that address.

Indeed, this seems to be the more important question. We would need to use a multicast address for publishing since we want all adapters to receive all such events for all tenants ...

**Comment by calohmn** [comment]
> Indeed, this seems to be the more important question. We would need to use a multicast address for publishing since we want all adapters to receive all such events for all tenants ...

So, this new multicast address would be needed for tenant/device updated/deleted notifications for now.
I think the first question here would be, whether we want to use a tenant-specific link address (like "notification/${tenant}"), or a fixed address (like "notification").
Going for a fixed address would mean:
- less link handling overhead in the adapters
- less management overhead of such addresses in the messaging network.

A tenant-specific address on the other hand would make this address potentially also available for northbound consumers.

I don't see much of a benefit in making these notifications available for northbound consumers, therefore I would prefer using a fixed address, making the "Notification API" more of a Hono internal API. @sophokles73 WDYT?

**Comment by sophokles73** [comment]
> I don't see much of a benefit in making these notifications available for northbound consumers, therefore I would prefer using a fixed address, making the "Notification API" more of a Hono internal API. 

+1

**Comment by sophokles73** [comment]
@calohmn Are you actually working on this?

**Comment by calohmn** [comment]
I had started working on it but I'm currently doing other things.

**Comment by sophokles73** [comment]
BTW this also applies to the AMQP adapter.
