### ISSUE TITLE
[#2837] Add AMQP based Notification Clients

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2983]
#2837 adds Hono internal notifications. The clients for sending and receiving notifications with Kafka already exist. Analogous implementations for AMQP are still missing.

**Comment by calohmn** [comment]
One thing that should be changed here is the way the `notificationSender` objects are handled in the device registry `ApplicationConfig`. 
Currently, there are 13 `KafkaBasedNotificationSender` objects being created - used in 2 different vert.x contexts. 
Only on 3 of these objects, the `start()` method gets called (relevant if `start()`  triggers connection creation and there is a readiness check associated with that).

The creation of 13 notification senders here is caused by the bean structure. For the `credentialsAmqpEndpoint` alone, there are for example 5 notification senders being created:
```
credentialsAmqpEndpoint
- credentialsService
  - credentialsManagementService (for the DeviceAndGatewayAutoProvisioner of the credentialsService)
    - notificationSender
    - tenantInformationService
      - tenantManagementService
        - notificationSender
  - registrationManagementService
    - notificationSender
    - tenantInformationService
      - tenantManagementService
        - notificationSender
  - tenantInformationService (used in credentialsService)
    - tenantManagementService
      - notificationSender
```
For the introduction of the `ProtonBasedNotificationSender` it should be prevented that there are 13 AMQP connections getting used.
