### ISSUE TITLE
Unable to register tenant using public key anchor

### ISSUE THREAD

**Issue by nehasewda** [eclipse/hono#2992]
I want to register a new tenant using self generated public key and private key. But, while giving curl command for the same, receiving the below mentioned error - 

curl command ->  **curl -i -H 'Content-Type: application/json' -H 'Expect:' --data-binary @tenant.json https://REGISTRY_IP:28443/tenant**

Error - 
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I am following the link - https://blog.bosch-si.com/developer/x-509-based-device-authentication-in-eclipse-hono/

Kindly help.

**Comment by sophokles73** [comment]
> I want to register a new tenant using self generated public key and private key.

Are you referring to a self signed certificate that you are using for the service endpoints of the protocol adapters and the device registry or do you want to use the certificate as a trust anchor for the tenant that you want to create? In any case, the error message seems to indicate, that curl does not trust the certificate that the registry endpoint has presented. In order to help you I will need to know how you have set up Hono. Did you use the Helm chart? Are you using the default configuration or have you e.g. configured your own key pair for the service endpoints?
