### ISSUE TITLE
Will the 1.10.0 version of Hono affected by apache log4j vulnerability(CVE-2021-44228)?

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#3000]
Hi team,

Will the 1.10.0 version of Hono affected by apache log4j vulnerability(CVE-2021-44228)?

Thanks

**Comment by sophokles73** [comment]
Hono's components do not use the log4j-core library so they are not affected by this vulnerability. However, the Infinispan data grid that can be used with Hono does use lo4j-core and is affected in most recent versions. The risk can be mitigated by setting the `LOG4J_FORMAT_MSG_NO_LOOKUPS` environment variable to value `true` on the Infinispan process/container (see https://www.docker.com/blog/apache-log4j-2-cve-2021-44228/ for a more detailed description).

It will also be a good idea to configure Infinispan to not expose any of its endpoints to public internet in order to minimize exposure.

**Comment by gongzhao2** [comment]
Thanks for your information.
I think we can close this question.
