### ISSUE TITLE
"Find" operation is missing in the device registration API

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#302]
There is no description about "find" operation in the device registration API documentation page.

**Comment by sophokles73** [comment]
That is because there is no such operation. We originally had one implemented in the *demo* Device Registry but it has never been part of the *official* API.

With the moving of the REST API from the REST Adapter to Device Registry I have now removed it completely. IMHO it does not really serve a useful purpose anyway. In production systems implementors will most likely provide much more sophisticated search operations anyway.

**Comment by ppatierno** [comment]
So can I remove the `find` method in the `RegistrationClientImpl` if we don't have the counterpart in the API anymore ?

**Comment by sophokles73** [comment]
Yes, I think we should. Or do you see any strong argument for actually defining it in the API?

(fingers crossed that you don't)

**Comment by ppatierno** [comment]
Don't worry I don't even because imho the device registry API for Hono should be simple like the operations we have today. Searching operations with parameters are more complex and can be different between implementors so we don't have to limit them with the API interface. I'm going to delete it ;)

**Comment by ppatierno** [comment]
@sophokles73 but I still see `findDevice` in the `RegistrationService` interface and handled by the `BaseRegistrationService`. Did you remove the operation only from the REST adapter or I'm missing something ?

**Comment by sophokles73** [comment]
yes, please remove it from there as well. Get rid of the little devil altogether ;-)

**Comment by sophokles73** [comment]
would be great if you could get this into M8

**Comment by ppatierno** [comment]
Closing on behalf of 4bf2efd52d1e33ea7d4c6b0d966fb0bd777e0eb6
