### ISSUE TITLE
Adding content-type as JSON for Device Registration API packets

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#318]
The Device Registration API related operations have some JSON payloads (i.e. device registration, get device, assert registration and so on). Maybe it could be worth to add the `content-type` AMQP system-property with `application/json` value to have a more detailed specification and corresponding packets. Wdyt ?

**Comment by sophokles73** [comment]
we (I?) explicitly kept this out in order to keep (better) interoperability with JMS clients accessing the API. There (currently) is no way for a JMS client to specify a content type of a binary payload :-( So, for the time being, we expect the payload to be JSON but do not require a corresponding AMQP property.
Makes sense?

**Comment by ppatierno** [comment]
I'm starting to hate the JMS compatibility issue ;)
