### ISSUE TITLE
Will the hono affected by CVE-2022-22965?

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#3189]
Hello Team,

Will the Hono affected by CVE-2022-22965?
https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

**Comment by sophokles73** [comment]
No, Hono does not use the web server based functionality of Spring Boot. Hono only uses Spring (Boot) for binding environment variables to configuration objects. Note that in Hono 2.0.0 the dependencies on Spring artifacts will be gone altogether because we will then have completed our migration to Quarkus.

**Comment by gongzhao2** [comment]
Thanks!
