### ISSUE TITLE
Status is reported as "String" instead of "int"

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#380]
The Hono documentation states that the "status" response will be reported as "int" [1]. However, looking inside the application properties of the AMQP message it actually is a "String".

![image](https://user-images.githubusercontent.com/202474/31818740-b3fc1f20-b599-11e7-85d2-231307f773ea.png)

[1] https://www.eclipse.org/hono/api/Device-Registration-API/#standard-response-properties

**Comment by sysexcontrol** [comment]
Thanks for reporting!
Same holds true for the Credentials API.

**Comment by sysexcontrol** [comment]
Changed the description (and not the code).
@sophokles73 : do you have any concerns regarding that?
Thus closing the issue now.

**Comment by sophokles73** [comment]
I do have concerns and I would rather have the status property be conveyed as an integer in the AMQP messages as specified originally and have the bug fixed in the code. The status codes we use are the ones defined by HTTP and are clearly integers so I do not see why we should treat them as strings.
In addition to that, the specification of `UTF8` is superfluous because in AMQP all strings are UTF8 encoded.

**Comment by sophokles73** [comment]
@sysexcontrol will you be able to roll back your changes and fix the bug (I mean work time wise)? Otherwise I will be happy to fix it ...

**Comment by sysexcontrol** [comment]
@sophokles73 : Yes, I can do it and will come up with the changes. Regarding the UTF-8 specification:
this was present at several places already, so it should disappear at other places that were not changed during this commit as well (which is fine IMHO). Will see where it is found and eliminate them.

**Comment by sysexcontrol** [comment]
Changed type of status to int (code AND changed back in description).
Fixed with 9f85364 and 4561472.

**Comment by ctron** [comment]
Thanks for fixing this!
