### ISSUE TITLE
Provide Helm Charts for deploying Hono to Kubernetes

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#413]
Currently, Hono project provides container images and some example Kubernetes resource files. That's already great for quickly spinning up a demo setup.

However with the upcoming of Kubernetes Helm there is now a mean to further simplify those steps.

In addition this would make things easier for people operating Hono, as they could use the provided Charts directly and maintaining the k8s resource files becomes obsolete.

Personally I would prefer to bundle the services by pieces that belong together:

* Each protocol adapter bundled separately
* Metric bundled together (Grafana + Influx)
* Messaging bundled together (Artemis, Qpid, Hono Messaging)
* Device Registry and Hono Authentication bundled separately

**Comment by sophokles73** [comment]
This sounds like a great idea :-) In fact, we have been thinking about providing Helm charts for Hono for some time already but haven't started work on it yet, so your engagement is more than welcome.

Regarding the scoping of the individual charts I have some concerns regarding bundling Hono Messaging with Artemis and Qpid because the *AMQP 1.0 Messaging Network* (Artemis + Qpid) is not *per se* a part of Hono and it should be easy to use another implementation (e.g. enMasse). IMHO we should therefore use a separate chart for the messaging network.

**Comment by pho-enix** [comment]
I absolutely agree with you regarding messaging. All parts should be as independent as possible and should be easy to be replace by another implementation.

To go forward, I will go ahead and prepare a PR for a protocol adapter chart.

**Comment by sophokles73** [comment]
@dejanb can we close this issue?
