### ISSUE TITLE
Three different response over three calls for Telemetry/Events

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hono#422]
Hi all,

Making 3 calls in succession gives different responses. First 401, then 503 then a 202.

I think I saw a documentation somewhere saying this is to be expected. However this is detrimental to applications using this API (or any Hono API for that matter). (e.g. Any application using this API would need to know to call again..) I think this happens for the other non-telemetry APIs as well.

Zubairs-MacBook:Downloads zubair$ curl -X POST -i -u ZZZZ@DEFAULT_TENANT:ZZZZ -H 'Content-Type: application/json' --data-binary '{"temp": 12}' http://localhost:8080/event
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Hono"
Content-Length: 12

Zubairs-MacBook:Downloads zubair$ curl -X POST -i -u ZZZZ@DEFAULT_TENANT:ZZZZ -H 'Content-Type: application/json' --data-binary '{"temp": 12}' http://localhost:8080/event
HTTP/1.1 503 resource limit exceeded
Retry-After: 2
Content-Length: 23

Zubairs-MacBook:Downloads zubair$ curl -X POST -i -u ZZZZ@DEFAULT_TENANT:ZZZZ -H 'Content-Type: application/json' --data-binary '{"temp": 12}' http://localhost:8080/event
HTTP/1.1 202 Accepted
Content-Length: 0

**Comment by sophokles73** [comment]
As you pointed out correctly, this has been expected behavior for clients that publish the first telemetry/event message for a tenant after startup of Hono or after the security token issued by Hono Auth to a protocol adapter has expired (by default, every 10 minutes).

That said, we have made several changes/improvements recently that should prevent this from happening in most cases. Have you experienced this behavior when using a very recent nightly build as well?

Apart from that, a client device publishing telemetry data should always be prepared to handle a 503 response because Hono does not accept any telemetry data from devices if there are no downstream consumers that are interested in telemetry data from corresponding tenants.

**Comment by zubairhamed** [comment]
I must confess, i've only tested this with 0.5-M10 release.

I am seeing this even after Hono has warmed up (i.e. it has been running after a while but after a period of inactivity) and with connected consumers.

Interestingly enough, after killing off consumers and having no consumers running, it still is able to accept telemetry :)  Is there a period before credits fall back to 0?

**Comment by sophokles73** [comment]
> I am seeing this even after Hono has warmed up (i.e. it has been running after a while but after a period of inactivity) and with connected consumers.

As I mentioned, this happened also when the security tokens expired (after 10 minutes by default).

> Interestingly enough, after killing off consumers and having no consumers running, it still is able to accept telemetry :) Is there a period before credits fall back to 0?

Yes, this is because the Qpid Dispatch Router issues 250 credits to Hono as soon as a first consumer connects (regardless of how many credits the consumer issued to the dispatch router). Once the consumer disconnects, Hono will accept telemetry messages until the remaining credits have been used up. This is because the *proton* library that we use as the AMQP 1.0 protocol implementation does only send *flow* frames to replenish a sender with *additional* credits but never to block it (by sending a flow frame with 0 credits). That is an implementation choice made by the Apache Qpid project which we have no influence on.

**Comment by zubairhamed** [comment]
Ah ok good info to know!

**Comment by zubairhamed** [comment]
If this is a known "issue" with a corresponding issue for a fix, i'll close it.
