### ISSUE TITLE
Rename REST adapter to HTTP adapter

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#435]
Currently, at most places we name our HTTP protocol adapter "REST adapter".

However, we do not have a REST semantic implemented. E.g.
- PUT on `/telemetry/<tenant>/<device>` is not an update on the properties of a device, but uploads a message created by this device
- POST on `/telemetry` (in case of authenticated devices) does not create a new device, but instead uploads a message created by the device that is uniquely identified by the also provided credentials

So I propose to rename the adapter everywhere from "REST adapter" to "HTTP adapter" (there are already questions regarding REST semantic coming in for which we cannot provide a satisfying answer).

@sophokles73 @ppatierno @pellmann  @dejanb : 
WDYT?

**Comment by sophokles73** [comment]
I share your feelings regarding the naming of the adapter. When we started to create it we had *good intentions* but I guess the [requirements for calling it *RESTful*](https://en.wikipedia.org/wiki/Representational_state_transfer#Architectural_constraints) cannot be met by the adapter due to its purpose anyway.

So, I am fine with renaming it to *HTTP adapter*.

**Comment by ppatierno** [comment]
I totally agree on changing the name to HTTP adapter. From the beginning I didn't like "REST adapter" so much because the REST architecture isn't strictly related to the protocol used for providing its semantics (the majority of developers use HTTP of course, but you can implement REST with other protocols as well). 

So my +1 for HTTP adapter !

**Comment by sysexcontrol** [comment]
Thanks for your votes!
I will rename it then (today I guess), to have it correctly named for the upcoming Newsletter article already.

**Comment by sysexcontrol** [comment]
Remark: several documentation updates still pending.

**Comment by sophokles73** [comment]
fixed in a38c515f0dcb865163d3c1d3baf13c6bdf205689
