### ISSUE TITLE
AMQP message annotations unnecessary for all RequestResponse APIs

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#469]
Currently, the registration, credentials and tenant API all determine the tenantId (and some more values) and annotate the message with them.

This seems unnecessary and should (if appropriate) be eliminated for all these APIs. Instead, the implementation should stick strictly to where the necessary values are defined in the API specification: e.g. the appplication properties.

**Comment by sophokles73** [comment]
It seems that we originally added the annotations because the APIs do not require the clients to include the tenant ID in the request messages but we do need the tenant ID in the service implementations.
I'll think about this a little and see if we can get around adding the annotations, but if not, it's no big deal either.
