### ISSUE TITLE
DNS resolve in azure aks kubernetes cluster seems to behave strange

### ISSUE THREAD

**Issue by bsukramlitt** [eclipse/hono#490]
**VERSION** M11-SNAPSHOT
**ISSUE**: DNS resolves not correct 
**ENV**: Microsoft AKS Kubernetes Cluster

cat /etc/resolv.conf
```
nameserver 10.0.0.10
search hono.svc.cluster.local svc.cluster.local cluster.local randomname12315135153.ax.internal.cloudapp.net
options ndots:5
```

**BEHAVIOUR**: 
`someaddressregisterd.servicebus.windows.net ` gets resolved/changed to `someaddressregisterd.servicebus.windows.net.randomname12315135153.ax.internal.cloudapp.net`
where randomname12315135153.ax.internal.cloudapp.net is the last search entry in resolv.conf

hono-service-messaging log:
```
11:59:10.665 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqp://someaddressregisterd.servicebus.windows.net:5671]
11:59:11.176 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://someaddressregisterd.servicebus.windows.net:5671]: Search domain query failed. Original hostname: 'someaddressregisterd.servicebus.windows.net' failed to resolve 'someaddressregisterd.servicebus.windows.net.5ktyvdc02vkuti5b2n4gshahuf.ax.internal.cloudapp.net' after 3 queries
11:59:11.177 [vert.x-eventloop-thread-1] INFO  o.e.h.t.i.ForwardingTelemetryDownstreamAdapter - failed to connect to downstream container: Search domain query failed. Original hostname: 'someaddressregisterd.servicebus.windows.net' failed to resolve 'someaddressregisterd.servicebus.windows.net.5ktyvdc02vkuti5b2n4gshahuf.ax.internal.cloudapp.net' after 3 queries
```
nslookup someaddressregisterd.servicebus.windows.net works (ip and hostname resolves)
ping someaddressregisterd.servicebus.windows.net works (ip resolves)
telnet someaddressregisterd.servicebus.windows.net 5671 works 
custom qpid client deployed to the same cluster connecting same address works 

**EXPECTED**
someaddressregisterd.servicebus.windows.net can be resolved correctly

**Comment by sophokles73** [comment]
The problem seems to be the
```
options ndots:5
```
in the resolv.conf. vert.x' DNS resolver actually considers this option and thus appends the local search domain to names that contain less than 5 dots before resolving them. In your case the name to resolve contains four dots only and thus the resolver appends the search domain.

You may be able to circumvent the problem by creating a Service without a selector or an *ExternalName* typed Service for your external host name as [described here](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors)

**Comment by bsukramlitt** [comment]
After I created a ExternalName service:
```
kind: Service
apiVersion: v1
metadata:
  name: az-service-bus
  namespace: hono
spec:
  type: ExternalName
  externalName: external-bus-address.servicebus.windows.net
```

the error behaviour changed but didn't resolved

```
14:20:41.511 [vert.x-eventloop-thread-1] INFO  o.e.h.t.i.ForwardingTelemetryDownstreamAdapter - failed to connect to downstream container: 
connection timed out:  az-service-bus.hono.svc.cluster.local/1.2.3.4:5671
14:20:41.515 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://az-service-bus:5671]: 
connection timed out: az-service-bus.hono.svc.cluster.local/1.2.3.4:5671
14:20:41.516 [vert.x-eventloop-thread-1] INFO  o.e.h.e.i.ForwardingEventDownstreamAdapter - failed to connect to downstream container: 
connection timed out: az-service-bus.hono.svc.cluster.local/1.2.3.4:5671

``` 
any suggestions?

**Comment by sophokles73** [comment]
I think that this is because the *ExternalName* service simply returns the *external* CNAME which still needs to be resolved to an IP address by Hono Messaging, facing the same problem as before. Maybe you can try to create a Service without a selector instead for which you also create an Endpoints resource manually using the external service's IP addresses. This way we may at least verify if this is indeed the problem...

**Comment by sophokles73** [comment]
You can also try to explicitly set the ndots option on the vert.x resolver used in Hono Messaging by adding the following line at https://github.com/eclipse/hono/blob/394644ed47dbffff44d9cd64ea61e49a758730ff/services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplicationConfig.java#L68

`.setNdots(2)`

The vert.x DNS resolver should then ignore the setting of ndots:5 in the resolv.conf and resolve domain names which contain at least two dots *as is*, i.e. without appending the local search domain.

If this works we could make this option configurable via an environment variable.

**Comment by bsukramlitt** [comment]
I can now confirm that the issue is not related to k8s at all. Yes there was a DNS issue but the ExternalName service resolved it. Also a local test shows the same behaviour.  

Right now I think the issue belongs to erros of mine regarding hono configuration which is as follows:

application.yml
```
  downstream:
    host: some-service-bus.servicebus.windows.net
    port: 5671
    tlsEnabled: true
    username: User
    password: Password

```

May I need to set something differently?!

To ensure that vertx proton is the case I used a vertx proton hello world to connect my broker like so:
```
public static void main(String[] args) {

    // Create the Vert.x instance
    Vertx vertx = Vertx.vertx();
    Transport transport = Proton.transport();
    ProtonClientOptions options = new ProtonClientOptions();
    options.setSsl(true);
    // Create the Vert.x AMQP client instance
    ProtonClient client = ProtonClient.create(vertx);

    client.connect(options,"some-service-bus.servicebus.windows.net", 5671, AZURE_SAS_NAME, AZURE_SAS_KEY, res -> {
      if (res.succeeded()) {
        System.out.println("We're connected");
        ProtonConnection connection = res.result();
      } else {
        res.cause().printStackTrace();
      }
    });
  }
```

As this works I checked how the ProtonClient in Hono is initialized and so far found no difference which would explain to me why the plain proton impl works in contrast to the hono downstream vertical. 

Right now I'm stripping down the hono code to identify the issue. Any hints are appreciated.

**Comment by sophokles73** [comment]
In your application.yml for Hono Messaging you should use *az-service-bus.hono* as the downstream hostname in order to actually use the ExternalName typed Service you created. 

In fact, the logs you included
'''
14:20:41.511 [vert.x-eventloop-thread-1] INFO  o.e.h.t.i.ForwardingTelemetryDownstreamAdapter - failed to connect to downstream container: 
connection timed out:  az-service-bus.hono.svc.cluster.local/1.2.3.4:5671
14:20:41.515 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://az-service-bus:5671]: 
connection timed out: az-service-bus.hono.svc.cluster.local/1.2.3.4:5671
14:20:41.516 [vert.x-eventloop-thread-1] INFO  o.e.h.e.i.ForwardingEventDownstreamAdapter - failed to connect to downstream container: 
connection timed out: az-service-bus.hono.svc.cluster.local/1.2.3.4:5671
'''
indicate that name resolution has worked and that the problem seems to be more related to the connection establishment. That could mean wrong username/password or non-trusted CA used by the remote server etc.

**Comment by bsukramlitt** [comment]
You are right about the connection establishment. I researched that part and found that the connection timeout seems to be hard coded to 200 ms at several places and I couldn't find a way to configure that. The initial connection to the azure service bus takes longer so the connection doesn't get established. If I override the timeout in org.eclipse.hono.connection.ConnectionFactoryImpl.connect(...)
by setting
clientOptions.setConnectTimeout(1000);

The connection can be established.

**Comment by sophokles73** [comment]
see #331

**Comment by sophokles73** [comment]
@bsukramlitt can we close this issue?
