### ISSUE TITLE
Extend Credentials API to support client context

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#504]
In order to be able to use client provided information during authentication process, we need to extend the existing Credentials API *get* operation with optional bag of properties. Credentials API implementation may then use this information in order to determine device identity. 
For example, MQTT clients always provide a MQTT *client-id* in the *CONNECT* packet.

**Comment by ppatierno** [comment]
> MQTT clients always provide a MQTT client-id in the CONNECT packet.

It's not always true, not mandatory by spec. The client-id can be zero bytes length and in this case the broker can assign a random client-id to the client (which in any case doesn't know what it is because it's not provided in the CONNACK). The `MqttServer` does that (it's configurable) but how it can be related with the Credentials API feature we are discussing ?

**Comment by sophokles73** [comment]
> It's not always true, not mandatory by spec. The client-id can be zero bytes length

That is true, however, the way I read the spec
> A Server MAY allow a Client to supply a ClientId that has a length of zero bytes, however if it does so the
Server MUST treat this as a special case and assign a unique ClientId to that Client. It MUST then
process the CONNECT packet as if the Client had provided that unique ClientId [MQTT-3.1.3-6].

the result will be the same, i.e. if the connection is established at all, the MQTT adapter will have a client-id at hand for the device, right?

**Comment by ppatierno** [comment]
I was referring to the the phrase : 

"MQTT clients always provide a MQTT client-id in the CONNECT packet"

It's not true. As the spec says and all the brokers implement, a client can avoid to provide a client-id. In this case two things can happen : 

- if clean session is true, the server accept the CONNECT and assigns a random client-id to the client for its internal handling but the client will never know this assigned client-id
- if clean session is false, the server refuse the connection because if the client wants to store the session on the broker, it has to provide the client-id needed by the server for handling such a session internally. (of course the randomly generated id is not useful, because the client doesn't know about that and can't provide on re-connection for recovering a previous session).

So "clients always provide a client-id" is not true, it can be empty.

> the result will be the same, i.e. if the connection is established at all, the MQTT adapter will have a client-id at hand for the device, right?

Btw you are right here, because the MQTT adapter knows the randomly generated client-id (the MQTT server does it by default but it can be changed) and its related MQTT connection.

**Comment by sophokles73** [comment]
@dejanb can we close this issue?
