### ISSUE TITLE
Resources status for Hono (Performance monitoring)

### ISSUE THREAD

**Issue by mohabh88** [eclipse/hono#533]
Is there a way to get the status of the resources for Hono using the performance measures (i.e., CPU, Memory usage, etc.)... the dashboards for minikube/minishift, for example, don't show such pieces of information. The dashboards just say running. Is there a way to do so?

**Comment by pellmann** [comment]
Hi,

you could activate a couple of metrics inside the services by adding this
to the yml files (or set it otherwise).

hono:
  metric:
    jvm:
      memory: true
      thread: true
    vertx: true

The metrics then will be written in the InfluxDB - but at the moment there
is no Grafana dashboard for it.

See https://github.com/eclipse/hono/issues/354. If you could add such a
dashboard for all services, this would be a big advantage!


2018-03-12 17:40 GMT+01:00 mohabh88 <notifications@github.com>:
