### ISSUE TITLE
Consider switching to Eclipse OpenJ9

### ISSUE THREAD

**Issue by kartben** [eclipse/hono#665]
I did a quick test switching a Docker Swarm-based deployment from OpenJDK to Eclipse OpenJ9, and it would seem that there is a significant improvement in terms of footprint (not surprisingly), and slightly better throughput for the adapters as well. Would it make sense for me to send a PR?

**Comment by sophokles73** [comment]
@kartben based on the positive feedback regarding OpenJ9 that I had received from the good people from the [Eclipse Ditto project](https://www.eclipse.org/ditto), I had already started thinking about experimenting with it. So, FMPOV a PR would be more than welcome :-)

@ctron @dejanb @pellmann @sysexcontrol @ppatierno WDYT?

**Comment by sysexcontrol** [comment]
Considering especially the smaller memory footprint after startup (https://www.eclipse.org/openj9/oj9_performance.html) that would ease the requirements for horizontal scale up, I give :+1: for experimenting with OpenJ9. 
The shown results look quite promising to me.

**Comment by ctron** [comment]
We plan to perform another scale test in our scale testing lab in the next few weeks. I think we could try to add this to the plan.

What we would need to do is to find a simple way to replace the OpenJDK VM with J9 in the S2I builder. As we already have a custom base image there, it should be simple to replace the VM.

**Comment by ctron** [comment]
After having a second look at this issue … do we need to "switch" to J9? In the end I think it shouldn't matter if Hono runs with OpenJDK or J9 as a VM, right?

**Comment by thjaeckle** [comment]
What you should be aware of:
The current 0.8.0 release of OpenJ9 does not handle signals correctly, so a `SIGTERM` signal for example cannot be handled by a registered JVM shutdownHook.

The upcoming 0.9.0 release will fix that. If you however do not have a shutdown hook (via `Runtime.getRuntime().addShutdownHook(...)`) registered (for example in order to gracefully leave a cluster), you should not have a problem here.

We noticed that too late :)

**Comment by sophokles73** [comment]
@thjaeckle thanks for the info :-) This would indeed be an issue for since Spring Boot does register a shutdown hook ...

**Comment by ctron** [comment]
Coming out of the scale test, we created a S2I drop-in replacement using OpenJ9 instead of OpenJDK, as a VM.

* https://github.com/ctron/s2i-java-openj9
* https://hub.docker.com/r/ctron/s2i-java-openj9/

The image can be used by replacing `fabric8/s2i-java` with `ctron/s2i-java-openj9` in the OpenShift template. I am not saying that this is a proper solution, but something which might help people give it a try, and easily switch back and forth between OpenJ9 and OpenJDK.

**Comment by sophokles73** [comment]
We should at least provide instructions on how to use Hono with OpenJ9.
