### ISSUE TITLE
Add the ability to specify an arbitrary "reply-to" address for command replies

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/hono#708]
Currently the reply-to address for sent commands is in the following format:
```
control/TENANT/4711/${replyId}
```
The `${replyId}` is created by the Hono-Client (or AMQP-client).

For Eclipse Ditto it would be really helpful if when sending a command the whole "reply-to" address could be specified, or at least the part after `control/TENANT`.

That way we could pass in for each command a common "catch all" address like for example:
```
control/TENANT/replies
```
Ditto would only have to attach to this address in order to get all command replies.

Background:
Ditto's connectivity is clustered among several cluster nodes. When a failover happens (e.g. because one node crashes, a Hono connection which was established on this node will be opened on a still "living" cluster node. The new node however can have no knowledge of the `${replyId}`s which were created on the other cluster node which crashed.

Would that be possible?
Feels like if the client already specifies the `${replyId}` it could also specify the whole address.

**Comment by sysexcontrol** [comment]
@thjaeckle : 
To complete the picture, there are currently already two variants:
- the Hono client generates a `replyId` and a receiver link is opened for `control/TENANT/4711/${replyd}`
- the application provides it's own `replyId`, that is appended to `control/TENANT/4711`

Probably it makes sense to change variant 2 to
- the application provides it's own `replyId`, that is appended to `control/TENANT`. To skip the tenant and let the application define this part as well seems to be more problematic, since the authentication to the AMQP network is on the level of the tenant. But this should be working well for Ditto, shouldn't it?

The `old` variant 2 would be substituted by the new one then, so there wouldn't be three variants.

**Comment by thjaeckle** [comment]
> But this should be working well for Ditto, shouldn't it?
Yes, it should. No need to skip the `TENANT`

**Comment by pellmann** [comment]
This would be a change in our API for the reply-to and the sender link address used by the adapter. But I think it makes sense to change it this way, as long as we stay with `control/tenant/` for authorization.

Before

`control/${tenant_id}/${device_id}/${reply-to}`

After

`control/${tenant_id}/${reply-to}`

and our Hono client by default will set  `${reply-to} ` as `${device-id}/something`

**Comment by sophokles73** [comment]
@pellmann @thjaeckle can this be closed?

**Comment by pellmann** [comment]
@thjaeckle - I think you should take look if this works for you.

**Comment by thjaeckle** [comment]
According to the adjusted Command-And-Control-API.md it will work for us.

**Comment by sophokles73** [comment]
@thjaeckle can you then close this issue?
Once we have rolled out 0.7-M2 and you had a chance to test it with Ditto, you can create a new issue if something doesn't work ...

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/b29f887b7e548725a8b6a6bead93ae2d162dc21d
