### ISSUE TITLE
RestFull API

### ISSUE THREAD

**Issue by narenrami** [eclipse/hono#726]
Is there a list of the RestFull API available for 

1. Create, Update, Delete and view devices under a tenant
2. Create, Update, Delete a device

I know we have the AMQP API ..

Thanks

**Comment by sophokles73** [comment]
There is no official API for doing this, simply because the device management component is not part of Hono. Instead, Hono relies on AMQP 1.0 based APIs for retrieving the relevant information it needs for running from an *existing* device management system.

That said, the *example* Device Registry component that is included with Hono (and which is **not** intended to be used in production environments), exposes such functionality by means of a set of HTTP endpoints which you can read about in the [Device Registry User Guide](https://www.eclipse.org/hono/user-guide/device-registry/).
