### ISSUE TITLE
Share downstream connection between adapters

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#73]
By now we have several adapters (telemetry, event and soon command) in Hono server which create new connections for sending/receiving messages to/from the Qpid Dispatch Router. This is done for every instance of the adapter (verticle). This could result in a larger number of connections. 
Does it make sense to share connection(s) between these adapters?

**Comment by sophokles73** [comment]
IMHO it does.

**Comment by ppatierno** [comment]
It could be a good idea even for the following problem I have just found out. My CPU has 8 cores so without specifying maxInstances (but leaving it to 0 so using the application.yml under config ), the Hono server application deploys 8 verticles and for each of them 2 downstream endpoints (telemetry and event). The result is the needed for 8 x 2 = 16 connections. The current internal-vhost policy has following parameters : 

"maxConnectionsPerUser": 10,
"maxConnectionsPerHost": 10,

So in my scenario following errors come : 

11:27:21.565 [vert.x-eventloop-thread-13] WARN  i.v.proton.impl.ProtonConnectionImpl - Connection closed with error
io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:resource-limit-exceeded, description='connection disallowed by local policy', info=null}

It means that for 3 remaining verticles, the related 2 endpoints connection aren't actived .. so 3 verticles are useless and can't forward messages downstream.

Of course it doesn't happen using docker-compose because the maxInstances is set to 1.

We should find a way with docker-compose to have the env variable HONO_MAX_INSTANCES used for building the right values for above connections max policies.

**Comment by sophokles73** [comment]
In contrast to what I had stated earlier, I have changed my mind regarding sharing the downstream connection. I no longer think that it is a good idea to share the connection:

1. In many cases the service component will be deployed to single processor/core VMs (e.g. t2.micro or t2.small on AWS) so there is nothing to be shared anyway.
2. In cases where the verticles are deployed multiple times, there is nothing that would/should prevent each of the verticles to connect to a *different* peer container. This would/could also help with distributing load more evenly among the peer containers.
