### ISSUE TITLE
Events are not durable

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#743]
The Hono documentation says Events should be flagged as *durable*, and for good reason[1]:

> Events provide a different quality of service for messages sent to the Event endpoint by setting the durable property of the message header to `true`.

However the outgoing messages are not set *durable*. There is a method `addEndpointSpecificProperties` which should take care of this, but it seems never to be called.

I think this originates from the confusing number of "send*" methods. Maybe it is time to clean those up.

[1] https://www.eclipse.org/hono/api/event-api/

**Comment by sophokles73** [comment]
This is due to the fact that the protocol adapters no longer route all messages through Hono Messaging, which so far has been (and still is) the place where the messages' *durable* flag has been set.

Now that we no longer use it, we indeed need to make sure that event messages have this flag set by `EventSenderImpl` before they are sent out to the peer.

> I think this originates from the confusing number of "send*" methods. Maybe it is time to clean those up.

I agree that we have more of those than we (currently) seem to need. However, they all have been there since the early days, so I am not sure which ones are actually being used and which ones could be safely removed. In the end, they are all part of Hono's public API ... Maybe we can ask on the mailing list if anybody would have a problem with eliminating the larger part of them or not. But for that we would need to have a specific list of the methods you would like to remove.
