### ISSUE TITLE
Services can be flooded with requests

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#756]
Pushing "too many" requests towards the Hono HTTP protocol adapter make it behave rather poorly. My expectation would be that Hono would still be able to handle the amount it can handle, but it looks to me as if the HTTP adapter mostly breaks down.

I tried to dig a little bit into this and I think I know one reason why this could be. Pushing HTTP requests  make the HTTP protocol adapter issues requests towards the device registry. If such a request cannot be handled in a specific amount of time (default 200ms) then it will be aborted and the HTTP request failed.

My understanding of the message flow is the following:

![request handling](https://user-images.githubusercontent.com/202474/43648168-f907dc12-9739-11e8-9054-6c62f032e8d9.png)

<details>
title Request handling

Client->+Endpoint: Send request
note right of Endpoint: Validate Request
Endpoint->EventBus: Publish request
Endpoint-->-Client: Accept request

note over  Client: New credits are available

note right of EventBus: Process request
EventBus->Endpoint: Publish response

Endpoint->+Client: Send response
Client-->-Endpoint: Accept response
</details>

This would mean that the client (the protocol adapter) can push at a higher rate than the EventBus/RequestProcessor/Verticle can handle. Building up requests and slowing down the process.

That would also mean that, if requests stay longer than 200ms in some kind of queue on the EventBus side, then they would time out on the Protocol adapter side. So once your are in state that the EventBus queue is at a size that requests have to wait more than 200ms, then all requests will timeout. Which in fact means that no HTTP requests will be accepted any more.

A possible solution for that problem would be to delay the accept of the request until the response was send. The reject or release could still be sent directly after the validation of the request.

Another possible solution would be to get rid of the EventBus completely. As some initial profiler run showed that most of the time is spent processing EventBus messages.

This may as well relate to issue #735.

**Comment by sophokles73** [comment]
> A possible solution for that problem would be to delay the accept of the request until the response was send. The reject or release could still be sent directly after the validation of the request.

I do not quite understand how this would help. If  the request messages take longer than 200 ms to process in the device registry, then the requests towards the registry will still time out in the adapter, because the response does not arrive in time (within 200 ms). The result should be the same: the adapter will reject HTTP requests with a 503, or am I mistaken?

Once the adapter runs out of credits from the registry, it should actually immediately return a 503 to clients without trying to invoke the registry.

Did you experience this same behavior using the "load test mode" of the registry, where it simply returns a response without looking up the data?

**Comment by ctron** [comment]
> I do not quite understand how this would help. If the request messages take longer than 200 ms to process in the device registry, then the requests towards the registry will still time out in the adapter, because the response does not arrive in time (within 200 ms). The result should be the same: the adapter will reject HTTP requests with a 503, or am I mistaken?

And that is what happens. Yet, on the device registry side, that request is still present and will be processed, delaying requests coming in after that. So all requests which arrive in the future will also time out.

> Once the adapter runs out of credits from the registry, it should actually immediately return a 503 to clients without trying to invoke the registry.

It does, but that is not the problem.

> Did you experience this same behavior using the "load test mode" of the registry, where it simply returns a response without looking up the data?

Yes.

Assuming you have a device registry which allows for 100 credits, but only can process 1 request a second and the timeout it one second. And the request rate is 10 requests per second:

On the first second, you have 10 accepted requests and 1 response. 9 timeouts. And 9 requests in the queue. As canceling requests doesn't remove them on the device registry side.

On the second you have 10 accepted requests, 1 response (already timed out), 10 timeouts and 18 requests on the queue …

**Comment by sophokles73** [comment]
So, then the issue actually seems to be the fact that the registry flows a credit to the adapter with each request message it accepts (due to the prefetch we set in `RequestResponseEndpoint.onLInkAttach`). 
We would need to change this to manual flow control and flow the credit back to the adapter only *after* we have sent back the response ... This way, we should be able to build up back pressure appropriately. WDYT?

**Comment by ctron** [comment]
You are right. That was a misunderstanding from my side about how it works. My understanding was that the disposition also handles the credit. Which it does not.

So the solution would be as you suggested, send the credit manually. I will create a PR and assign you as a reviewer.

**Comment by ctron** [comment]
Summarizing the discussion from IRC:

Currently there is the problem that, on the request/response service side, there is no correlation between the receiver of the request and the sender of the response. So it isn't possible to do proper credit tracking.

My proposal would be to re-structure the request/response functionality in a way that is uses the EventBus reply feature and use that as a way to send the response to the requestor. This also seems to appropriate way to use the EventBus from a vertx point of view.

For this to work, it is required though to know to which link to send the response to. For this, an in-memory map will be added, which records which senders are registered for each reply-to address.

This change would also eliminate the need the an explicit call to `consume` on the event bus, and thus resolves the memory leak described in #753.

**Comment by sophokles73** [comment]
> For this to work, it is required though to know to which link to send the response to. For this, an in-memory map will be added, which records which senders are registered for each reply-to address.
This change would also eliminate the need the an explicit call to consume on the event bus, and thus resolves the memory leak described in #753.

I agree that this will prevent EventBusConsumers to leak in the situation described in #753. However, it will introduce another potential leak: when a client breaks away, we still need to make sure that the sender gets removed from the map. So, in any case we need to deal with clients breaking away unexpectedly.

I would therefore rather stick with the current implementation in order to not turn everything upside down (again), add the *sender/reply-to* map and make sure that we both close the corresponding EventBusConsumer and remove the sender from the map when a client disconnects (unexpectedly). The map can then be used to flow credit to the sender when a response message has been received from the event bus.

**Comment by ctron** [comment]
So yes, dying connections have to be handled in any case.

Using the "reply" functionality would definitely make the code more understandable IMHO. As there is clear connection between the request and the response. But yes, technically that will work as well, if you want to stick to the current pattern. Let me know and I will make a PR.

**Comment by sophokles73** [comment]
> Using the "reply" functionality would definitely make the code more understandable IMHO.

That might be true. However, the focus should be on fixing the memory leak for now. We can still change the code to use *reply* in a later PR.

So, please, just start with introducing the map and handling the unexpected disconnects ...

**Comment by ctron** [comment]
I created preview for a PR which shows in principal how the mapping credits work with the map. This is neither cleaned up, nor tested. Also the "connection lost" case of #753 is not yet handled.

**Comment by ctron** [comment]
Fixed with #760
