### ISSUE TITLE
New Bcrypt credentials enables DoS attack on the protocol adapters.

### ISSUE THREAD

**Issue by balsmn** [eclipse/hono#825]
As per Credentials API, Hono is using Spring security for Bcrypt password encoding.

Spring security supports bcrypt password encoding with log rotations from 4 to 31, 10 being default (i.e:- 2^10 hash iterations). Once hashed, the log rotation used is part of the password like 

`$2a$21$LQdzaDSINBpHmYRiGEVtkOVt2GScZ6bPvEyoAIpiVIE6F4rviemdm`

where $21 represents the log rotation used. There is currently no max limit defined in Hono. If a user, say stores the password with higher rotation, then it could enable a DOS attack on the adapters.

I tested the time taken for `BCryptPasswordEncoder.matches` with higher log rotation on my laptop (Intel Core i7 - 2.7GHz 8 core, 32 GB RAM) it took

- 10 - 105 milliseconds
- 12 - 360 milliseconds
- 18 - 21 seconds
- 21 - 178 seconds
- 31 - more than 1 hour and I had to abort it.

Setting 31 as log rotation will definitely block the protocol adapters.

As a best practise, I would restrict the log rotation to 12 or 14, document them as part of credentials API and have this checked in 

org.eclipse.hono.util.CredentialsObject.hasValidSecrets()

**Comment by sysexcontrol** [comment]
@balsmn Thanks a lot for this detailed report!
IMHO very reasonable, I will schedule a fix for the next milestone 0.8-M2.

**Comment by sophokles73** [comment]
Nice catch @balsmn :+1: 
There seem to be two issues to consider in this context:
1. Make sure that we do not allow a DOS attack by registering a bcrypted password with more iteratins than seem reasonable.
2. Make sure that we do not block the event loop of protocol adapters that validate a password against a bcrypt hash.

The first item should probably be addressed by introducing a (configurable) upper limit to the Credentials endpoint implementation included in Hono. However, other Credentials API implementations that do not make use of the base classes provided by Hono will need to enforce such a limit themselves.

The second item needs to be addressed in Hono's `AbstractDeviceCredentials` class by scheduling the hash validation on a worker thread instead of running it on the event loop.

WDYT?

**Comment by balsmn** [comment]
>> The first item should probably be addressed by introducing a (configurable) upper limit to the Credentials endpoint implementation included in Hono. However, other Credentials API implementations that do not make use of the base classes provided by Hono will need to enforce such a limit themselves.

Yes it is a good idea to have a configurable upper limit in the base credentials implementation of Hono and for the implementation which is not based , I would recommend mentioning it in the credentials documentation of Hono so that it is not missed.

As far the second item, I see you have already merged the PR#833. Thank you very much for fixing it fast.

**Comment by balsmn** [comment]
Sorry, mistakenly closed the issued..

**Comment by sophokles73** [comment]
> Yes it is a good idea to have a configurable upper limit in the base credentials implementation of Hono and for the implementation which is not based on it, I would recommend mentioning it in the credentials documentation of Hono so that it is not missed.

@balsmn would you be willing to create a corresponding PR for implementing this in the Credentials endpoint base classes?

**Comment by balsmn** [comment]
@sophokles73 yes I can work on this PR sometime next week.

**Comment by sophokles73** [comment]
@balsmn no need to work on this. I am close to committing the missing functionality ...

**Comment by balsmn** [comment]
oh, I was about to start this now. Anyways. Thanks.
