### ISSUE TITLE
Using client identifier for authentication in MQTT adapter seems inappropriate

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#86]
When an MQTT client connects to the MQTT adapter, e.g. for uploading telemetry data, the adapter verifies that the *client identifier* provided in the client's CONNECT packet is the same as the *device_id* segment of the topic name (which needs to be of the form `telemetry/${tenant_id}/${device_id}`).

There are multiple concerns I have:
1. The client probably does not know the *logical* ID that Hono uses for referring to the device because the device's ID might be derived from a non-inherent property of the device, e.g. a label attached to it by the owner, instead of a *static* property like the device's serial number or MAC address.
2. The client identifier is required to be unique among the connected clients of an MQTT server. Using a (static) client identifier might interfere with this requirement.
3. The username/password fields defined for the CONNECT packet seem to be much more appropriate for actually authenticating the client (alternatively, the client could be authenticated based on a client certificate during a TLS handshake if the client connects over TLS).

Based on this I think that we should not use the client identifier for asserting that a client can only upload telemetry data for itself, but instead we should do the following:
1. Client connects with arbitrary client identifier providing either username/password or a client certificate (when using TLS). The client identifier is used for MQTT session management as specified by MQTT.
2. MQTT adapter verifies the client's identity by checking the password against a credential store (for now we could use Hono's Device Registry for maintaining the secrets but this is certainly something that we should better delegate to a dedicated identity management service) or verifying the client certificate chain up to a trust anchor.
3. MQTT adapter uses the authenticated client identity to look up the *logical* device ID and corresponding tenant ID using Hono's registration API. If no device is registered for the client's authenticated identity, the connection is closed.
4. Client sends a telemetry message using a topic of the form `telemetry/${tenant_id}`.
5. MQTT adapter verifies that the `${tenant_id}` from the topic name matches the tenant ID of the looked up device ID and (if it does) uses the logical device ID and tenant ID when forwarding the telemetry data to Hono's telemetry endpoint, i.e. using the original topic name as the link address and adding the logical device ID as the value of the `device_id` message properties as required by the telemetry API.

WDYT?

**Comment by crenz** [comment]
The device's identity needs to be established with a device-specific _technical_ ID as well as an authentication secret (e.g. PSK, username/pass). This technical ID needs to be known both to the device itself, as well as business applications that want to interact with it. If you want to separate technical ID and logical ID, I would suggest there need to be three different pieces:

1. An extension of the current device registration API where someone can register a technical ID as well as credentials, and Honor creates the _logical_ device ID that you refer to. Both then need to be stored in a kind of device registry, and the API should return the logical device ID to the caller.

2. Support in the protocol adapters to let devices sign up using technical ID and authentication secret (verified by protocol adaptor using the device registry). The protocol adaptor then informs the device about the logical ID to use to post/receive data.

3. A lookup API that allows (authorized) business applications to look up logical device IDs based on technical ID. Once the lookup is performed, business applications then use the logical device ID to interact with the device.

**Comment by ppatierno** [comment]
Just thinking loud ...

We are saying that a client has has two IDs : one "technical" and one "logical". The device knows only the "technical" one. The client-id field shouldn't be used for bringing the "technical" one but the best place should be username/password (username = "techincal" ID). So what we should bring inside the client-id ?
Remember that it NEEDS to be unique along all MQTT connected clients because as the MQTT specification says, if we have client with id=123 connected and another new client connects with same id=123, it steals the already opened connection (so the server has to close the "old" 123 client).

It's pretty clear what @sophokles73 explained in terms of steps but ... what happens in the command and control use case ? In this use case, the address is control/${tenant_id}/${device_id} where device_id should be (I guess) the "logical" one. The client doesn't know the logical one so how can it subscribe to the previous address in order to receive commands ?

Here comes the step 2 of @crenz  I think but ... what's the topic that an MQTT client should subscribe for receiving a message containing the "logical" ID ? Or is the adapter which should track the relationship between connected client and address for receiving commands ?

So it turns out that ...

- An MQTT client connects using username=technical-id + password (with which client-id ?)
- An MQTT client publishes telemetry data on telemetry/${tenand_id} but on the other side it's up to the adapter to attach a sender to telemetry/${tenand_id}/${logical_id}
- An MQTT client subscribes for commands on control/${tenend_id} but on the other side it's up to the adapter to attach a receiver to control/${tenand_id}/${logical_id}

The matching techical_id - logical_id is tracked by the adapter (but again what about the MQTT client-id) ?

**Comment by sophokles73** [comment]
@ppatierno 

I think you are raising some valid issues here. 

> The device knows only the "technical" one. The client-id field shouldn't be used for bringing the "technical" one but the best place should be username/password (username = "techincal" ID). So what we should bring inside the client-id ?

Well, what are all the existing MQTT client libraries putting in there if the user doesn't specify it explicitly? I guess it will be based on a UUID? I wasn't aware of the fact that a client can *steal* another client's session by simply using the same CLIENT_ID. On the other hand, if this is true, there is nothing preventing a device to use another device's *logical* ID (maybe based on *guessing*) as its client id and trying to *steal* that other device's session, thus impersonating that other device, is there? So we need to make sure that this doesn't happen in any case, regardless of what we use/allow for the client ID.

The main question seems to be: Does the (MQTT) client need to know its *logical* ID?

IIMHO this won't be necessary as long as we can make sure that the adapter can uniquely resolve the technical ID to a logical ID (within a tenant). We are already following this pattern with the telemetry direction, i.e. the messages carrying telemetry or event data are annotated with the *logical* device ID by the adapter. For the command & control case the adapter could e.g. open a link using a resource ID that also contains the *logical* device ID which it has resolved the client's *technical* ID to during authentication.

**Comment by ppatierno** [comment]
Based on the MQTT specification, a client can connect specifying a zero length client-id and in this case the MQTT broker should generate a random one for internal use. In any case, this information doesn't come back to the MQTT client so that it can't know what is the client-id assigned by the broker.

Based on that, if a client connects with a zero length client-id, it MUST set clean session = true otherwise the broker MUST refuse the connection. It's pretty clear that it's needed because for using clean session = false, the client MUST know it's client-id for next connections (and recovering its session).

So an MQTT client library is compliant to the standard if it doesn't put any client-id (i.e. auto generated UUID) not explicitly specify by the caller.

For now my MQTT server doesn't provide the auto-generation of a client-id for client with zero length client-id in the CONNECT packet but I have to add it for sure (it's on my todo list).

At this point ... could we force at adapter level a client-id zero length from the client ? (otherwise the adapter close the connection). In this case the client-id is under the adapter control which has to generate it and it should be difficult for other clients to steal it. I don't know if it could be an insane idea ... :-)
Just because it seems that client-id seems to be "useless" in our Hono logic.

**Comment by sophokles73** [comment]
I am not sure if we will be facing use cases where the client actually *needs* to be able to recover/resume a session (and therefore needs to know its client ID). If not, then I think generating the session ID in the adapter is the best way for making sure that they are unique.

However, IIRC from our meeting at EclipseCon Europe last October in Ludwigsburg, there was some very specific semantics attached to the client ID in Kura. Do you know anything about that?

Maybe @hekonsek  can help out with some info since he is now working on *Kapua* a lot?

In any case, we could implement a protocol adapter specific to Kura's and Kapua's needs in addition to the generic MQTT adapter ...

**Comment by ppatierno** [comment]
So my idea wasn't so insane :-)

No I don't know about Kura / Kapua needs around the MQTT client-id. 

@hekonsek and @ctron can give us more information I guess.

**Comment by dejanb** [comment]
Yes, Kura/Kapua use clientId as "logical" device identifier which is used later heavily in MQTT namespace. Here's the full Kura MQTT namespace reference

https://eclipse.github.io/kura/ref/mqtt-namespace.html#remote-osgi-management-via-mqtt

From all this, I think we should try to leave this mapping of technical to logical id flexible. The same stands for the conversion of the MQTT topics to Hono addresses. In this way we will be able to support different kind of MQTT devices with just configuration tweaks instead of completely different adapters.

**Comment by sophokles73** [comment]
Now that @sysexcontrol is working on #261 I have given this some more though. My current take on this is:
1. When a device tries to open an MQTT connection, the adapter takes the username/password from the device's CONNECT packet and uses it to determine the device's *logical* ID as follows:
    1. If the adapter is configured for *singleTenant* then assume that the device belongs to `DEFAULT_TENANT` and use the *username* from the CONNECT packet as *auth-id*. Otherwise, split the *username* around the `@` character and use the first part as the *auth-id* and the second part as the tenant ID.
    1. Adapter looks up the device's credentials using the *Credentials* API's *get* operation with the *auth-id* as determined in the previous step.
    1. Adapter verifies the credentials and establishes connection (or not). In this step the adapter also determines the *logical* device ID by reading it from the result returned by the *get* operation.
1. When the device sends a message to a topic, e.g. `telemetry/myTenant` the adapter verifies that the device indeed belongs to the tenant indicated by the topic name. If this is the case, the adapter gets a registration assertion for the device and sends the message downstream.

This way the device itself does not need to know its *logical* device ID. In single tenant environments it also does not need to know the tenant ID as well because in this case the topic name is just `telemetry` or `event`.

**Comment by sysexcontrol** [comment]
Actually, I just reviewed the current state of the credentials integration into the MQTT adapter and wondered about scenarios that would not need the clientId anymore.

And again read the last comment from @sophokles73.

I think this is a very good idea how to handle the topic and clientId in MQTT - now that we have the credentials API integrated into the MQTT adapter.

So, as the next step, I would continue the implementation as follows (repeating partially what @sophokles73 already wrote):

**multi tenant configuration**
- the logical deviceId (which is already retrieved via credentials GET operation) will be used to complete the Hono messaging topic, like: `/telemetry/<tenant>/<logicalId>`
- the check if the logical deviceId belongs to the tenant is made after the successful GET operation
- the clientId is not used in any means for authentication

MQTT topic used by the device: `/telemetry/<tenant>`

**single tenant configuration**
- as for multi tenant configuration, with the addition that the tenant is skipped as well

MQTT topic used by the device: `/telemetry`

**Open points**

1. should we allow fully qualified MQTT topics, although a reduced topic is sufficient? E.g. should we allow `/telemetry/<tenant>/<logicalId>`, although the `logicalId` is determined by the credentials GET? I suggest: No. It reduces clarity. WDYT?
2. if authentication is unconfigured (so no credentials are accessed), should we keep all like it was before? Meaning clientId as logicalId, fully qualified MQTT topics with logicalId at the end of the topic? I suggest: yes. WDYT?

@sophokles73 @ppatierno : can you give some short thoughts on that again? I would start to realize this proposal then...
The way it is currently realized and documented is contradictory and has to be changed IMHO...

Thanks!

**Comment by sophokles73** [comment]
ad 1) assuming that this is the case where authentication of devices is required, I think that we should allow the topic to contain a third path segment but simply ignore it. What would be the alternative, closing the connection? I do not think that this would be very helpful.
ad 2) I think in this case we should retrieve the device ID from the topic and not the MQTT client ID which I would rather not assign Hono specific semantics to.

**Comment by sysexcontrol** [comment]
ad 1) yes, in that case the connection would have to be closed. Not helpful, I agree, so skip it.

ad 2) since the clientId has some well defined semantic in MQTT ("stealing" or reusing the session e.g.) and also seems to have usages in Kura/Kapua, the logical deviceId should be retrieved from the topic, I agree. 


So, both answers make perfect sense to me. Will consider it in the implementation.

**Comment by ppatierno** [comment]
Without considering the connection "stealing" that is something that we don't need to support but what's the main reason to not use the standard field for client-id as MQTT protocol but adding it at the end of the topic ?

**Comment by sophokles73** [comment]
Sorry, I think I do not get your point.

**Comment by sophokles73** [comment]
fixed in ddf190d0650d8b60ccb176b133ae98e0eb6db58f
