### ISSUE TITLE
HTTP-Adapter: misleading error trace if client certificate check failed (but basic auth succeeded)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#895]
Using the Hono HTTP adapter with Jaeger tracing enabled, we see traces like this:
![http-adapter-trace](https://user-images.githubusercontent.com/891931/48414102-0870b380-e74a-11e8-82e2-82832011b7e8.png)

We use the device authentication via Basic Auth (which succeeded here) - the error above is about the failed attempt to verify the device using a client certificate (done before the basic auth check).

Having this marked as an error in the trace is somewhat misleading and makes it harder to filter the traces list for actual errors.

**Comment by sophokles73** [comment]
The `X509AuthHandler` starts a span for every request coming in and tries to verify the certificate chain provided by the client. However, if the client does not use a client cert for authentication (but e.g. Basic auth as in your example), then an error will be logged to the span and the handler fails with an *UNAUTHORIZED* error code (which is what it should do).

The obvious thing to do is not to log an error if the client does not provide a certificate in its request. However, we might also not create a span in the first place in this case, because apart from the fact that we tried to authenticate the client using a cert and could not, there is not much interesting information to be gathered here. WDYT?

**Comment by calohmn** [comment]
@sophokles73 I agree, if the client didn't provide a certificate with the request, I think there's no need to create a span in the first place.
