### ISSUE TITLE
Hono Sandbox returns status 403 on device registration

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#919]
When I try to create a device on the sandbox with: 
``` bash
curl -X POST -i -H 'Content-Type: application/json' -d '{"device-id": "4711"}' \
http://hono.eclipse.org:28080/registration/DEFAULT_TENANT 
```
I get the response:
``` http
HTTP/1.1 403 Forbidden
Content-Length: 0
```
Expected response is:
``` http
HTTP/1.1 201 Created
Location: /registration/DEFAULT_TENANT/4711
Content-Length: 0
```

**Comment by sophokles73** [comment]
I suppose that is because a device with ID `4711` is already registered for the default tenant ...
The sandbox doesn't allow you to *modify* existing entities but allows to *create* ones only. That is to prevent others from tampering with your data ...

**Comment by mbaeuerle** [comment]
Sorry, my mistake. Should have used a clearly unique id:

Request:
``` bash
curl -X POST -i -H 'Content-Type: application/json' -d '{"device-id": "d6558977-d05f-4a4f-9238-40f04fdec03e"}' \
http://hono.eclipse.org:28080/registration/DEFAULT_TENANT
```
Response: 
```
HTTP/1.1 403 Forbidden
Content-Length: 0
```

**Comment by ctron** [comment]
I have the same issue, however switching to a new tenant, instead of `DEFAULT_TENANT`, I can create new devices. I think we reached the tenant device limit:

~~~
[jreimann@jreimann ~]$ hat reg create 1202
Execution failed: Unexpected return code: 403 Forbidden
[jreimann@jreimann ~]$ hat tenant create foo
Created tenant: foo
[jreimann@jreimann ~]$ hat reg create 1202 -t foo
Registered device 1202 for tenant foo
~~~

**Comment by sophokles73** [comment]
Yes, it seems that there are already 100 devices registered for DEFAULT_TENANT ...

**Comment by sophokles73** [comment]
with the upcoming 0.8 release I will delete all registered data on the sandbox once again. However, you should create your own tenant in any case for your experiments ...

**Comment by mbaeuerle** [comment]
I see, thanks! When creating my own tenant there is no issue creating a device.
