### ISSUE TITLE
[hono-rest-adapter] Refactoring regarding custom http binding

### ISSUE THREAD

**Issue by JanLoebel** [eclipse/hono#98]
Hi everyone,

I want to propose a small refactoring regarding the hono-rest-adapter. I think there will be people which want to customize the endpoints the rest adapter is binding to. For example, there can be device's which are already able to register and update telemetry data with pre-configured endpoints. So you could simply create an hono-rest-adapter with that endpoint binding.

The idea would be to move the current VertxBasedRestProtocolAdapter implementation to a more abstract class and provide a default implementation for that as long as no other instance on the classpath is provided. So everybody could extend the hono-rest-adapter and provide a custom Vert.x-Http-Route-binding.

Any ideas, feedback or suggestions here?

Best regards,
Jan

**Comment by sophokles73** [comment]
Sounds like a great idea :-) However, I would rather propose to extract an abstract base class (and e.g. move it to the `hono-core` module) so that other can extend it to build their own protocol adapters (in separate modules).

**Comment by ppatierno** [comment]
Just to clarify ... are you saying that ... 

Instead of just send telemetry data to the fixed HTTP endpoint : 

http://127.0.0.1:8080/telemetry/DEFAULT_TENANT/4711

you can have an adapter whit an endpoint for example like 

http://127.0.0.1:8080/myendpoint/4711

which routes traffic to the Hono telemetry address : telemetry/DEFAULT_TENANT/4711 ?

**Comment by sophokles73** [comment]
The idea is that you can implement a *custom* adapter that understands your device's existing (and not easily changeable HTTP based protocol) on to of an abstract base class that provides support for mapping the device's requests to Hono's API by means of a `HonoClient` instance the base class provides ...

**Comment by ppatierno** [comment]
So what I wrote is a simple example of that :-)

**Comment by sophokles73** [comment]
I guess so :-) I just wanted to point out that we should/would not sacrifice the *standard* REST protocol adapter but instead provide more options for people to connect additional devices that require their own resource layout ...

**Comment by JanLoebel** [comment]
I published some changes into my fork. Before creating a PR I wanted you to have a look at it first. So feel free to add some comments.

**Comment by sophokles73** [comment]
I have taken a look at your branch. This looks like a good start. I have left some comments, in particular I am not very convinced of the `HonoServiceUnavailableException` and its usage, though...

**Comment by calohmn** [comment]
A note on where to put the abstract base class:
Putting it in the `hono-core` module might not be a good idea because that would cause the `hono-core` module to need an additional dependency on the `hono-client` module (the base class contains a `HonoClient` instance). 
A better possibility imho would be putting the base class in a new `hono-adapter-http-base-vertx` module and adding a dependency on that module in the `hono-adapter-rest-vertx` module.

**Comment by calohmn** [comment]
I have created #119 to introduce a base class for HTTP-based protocol adapters.

Since the focus of custom HTTP protocol adapters is probably on the Telemetry and Eventing API, these are supported via the base class (Registration API support is still in VertxBasedRestProtocolAdapter).

**Comment by sophokles73** [comment]
fixed in 88d21df788b44ed68fb4561299594ce17feec717
