### ISSUE TITLE
Extract data from hono

### ISSUE THREAD

**Issue by shailesharya** [eclipse/hono#994]
Hey,
How can I extract data coming from devices to hono.
It's fine that devices send updates through desired protocols and then hono send msg through AMQP to the respected client
But is there any universal Java or python code available through which I can extract data and show the results on some gui like grafana or store data to database like influxDB.
THANKS.

**Comment by sophokles73** [comment]
Since Hono is inherently payload agnostic, I am afraid that Hono itself does not provide such means.
However, you may want to take a look at the Apache Camel project which can be used to implement Enterprise Integration Patterns and which also supports receiving and sending of AMQP 1.0 messages. So you could use it to build a Camel *route* which consumes data from Hono, parses its payload and POSTs it to e.g. InfluxDB via its HTTP API.

**Comment by shailesharya** [comment]
Can it be done without using Apache camel
Like any web socket program or python or Java code?

**Comment by sophokles73** [comment]
Sure, just use any AMQP 1.0 library in the programming language of your choice. We use Apache Qpid proton-j together with vertx-proton when running on vert.x. You can also use the Qpid JMS provider from Java if you prefer to use the JMS API. You can find example code for both in the integration test folders.
